### ISSUE TITLE
broken metamodel generation for @NotNull byte[] with javaee 8 api 

### ISSUE THREAD

**Issue by priyanahata** [eclipse-ee4j/eclipselink#1004]
in that case we need exact and reproducible test case as the test introduced with the fix through ##967 is not failing...

_Originally posted by @lukasj in https://github.com/eclipse-ee4j/eclipselink/issues/998#issuecomment-761081594_

Test case attached to 998 https://github.com/eclipse-ee4j/eclipselink/issues/998

**Comment by lukasj** [comment]
fixed
