### ISSUE TITLE
Automatic entity validation for Container Constaints, doesn't work

### ISSUE THREAD

**Issue by kronos72it** [eclipse-ee4j/eclipselink#1006]
I already opened this issue upon eej44/jpa-api but someone said isn't the correct place ,just because I used EclipseLink as provider in persistence.xml
Anyway this issue is reproducible with both EclipseLink or any provider.
The issue : 

I need to validate a JPA entity Transaction) with custom constraint when receiving a List . Then I create a Custom Constraint Annotation:
`@Target({ ElementType.TYPE,ElementType.TYPE_USE })
@retention(RUNTIME)
@documented
@constraint(validatedBy = { TransactionValidator.class})
public @interface TransactionValid {

String message() default "{org.hibernate.validator.referenceguide.chapter06.classlevel." +
"ValidPassengerCount.message}";

Class<?>[] groups() default { };

Class<? extends Payload>[] payload() default { };

LoadValues type() default LoadValues.MOV;

@interface List {
TransactionValid[] value();
}
}`

And referenced Validator :
`public class TransactionValidator implements ConstraintValidator<TransactionValid,Transaction>{

@override
public void initialize(TransactionValid constraintAnnotation) {
//throw new UnsupportedOperationException("Not supported yet.");
}

@override
public boolean isValid(Transaction t, ConstraintValidatorContext context) {
try {
ValidatorObject validator=new TransactionValidatorLogic();
validator.validate(t);
}
catch (ConstraintViolations ex) {
for (String s :ex.getViolations())
context.buildConstraintViolationWithTemplate(s).addConstraintViolation();
return false;
}

return true;

}

}`

Then , in my EJB I have the method receiving the List of Transaction :

`public void loadTransactions(List<@TransactionValid Transaction> q,final DataInfo info) throws HBException { 
// some other stufs 
try{ 
    for (Transaction t : q){ 
       em.persist(t); 
    }
 } 
catch (Exception e){ 
    if (e instanceof ConstraintViolationException){ } .... }`

Now I am expecting to get a breakpoint on my Custom Validator but it seams no Validation take place .

Thi is an EAR project with EJB and WEB modules . IN the EJB pom I used :

`<dependency> 
<groupId>jakarta.platform</groupId> 
<artifactId>jakarta.jakartaee-api</artifactId> 
<version>9.0.0</version> 
<scope>provided</scope> 
</dependency>`

And my persistence.xml is :
`<?xml version="1.0" encoding="UTF-8"?> <persistence version="3.0" xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://jakarta.ee/xml/ns/persistence http://xmlns.jcp.org/xml/ns/persistence/persistence_3_0.xsd"> 
<persistence-unit name="HB_PU" transaction-type="JTA"> 
<provider>org.eclipse.persistence.jpa.PersistenceProvider</provider> 
<validation-mode>AUTO</validation-mode> 
<jta-data-source>jdbc/hb_ds_admin</jta-data-source>
 <! -- some class listed --> 
<exclude-unlisted-classes>true</exclude-unlisted-classes> 
<properties> 
<property name="eclipselink.target-database" value="MySQL"/> 
</properties> 
</persistence-unit> 
</persistence>`

As you cans see I added the property validation-mode though it is not needed states the Jakarta Persistence Specification 3.0 .The specifiaction states that by default the AUTO value is setted and by the way the validation Bootstrap will be done by Container looking in the List and applying the Validation to all item in the List ,then what I am wrong ? it is a bug ?
If I apply the @TransancionValid annotation to Transaction Entity this working correct and fire up my Validator.
Elsewhere ,I doen't see any validation in debugging ,any breakpoint stop on Validator!

**Comment by rfelcman** [comment]
Hello,

I checked attached description and I'm missing there JPA Entity definition. Could You please provide it.
The best way is to check, modify and upload back attached test case. In attached test case I tried to implement provided annotation and validator `com.oracle.jpa.bugtest.domain.TransactionValid`, `com.oracle.jpa.bugtest.domain.TransactionValidator`, but currently it's not applied to test entity `com.oracle.jpa.bugtest.domain.TestEntityMasterAnnotated` due missing implementation details.
Test case contains all required dependencies for JPA bean validation in JSE environment see `pom.xml`. To try it locally You have to modify JDBC connection settings in `persistence.xml` and create DB table by `init.sql` script. Expected DB is MySQL.
Test case if functional, there is just for example one bean validation applied to `com.oracle.jpa.bugtest.domain.TestEntityMasterAnnotated#name
[jpa-bug-1006-AutomaticEntityValidationForContainerConstaints.tar.gz](https://github.com/eclipse-ee4j/eclipselink/files/6028266/jpa-bug-1006-AutomaticEntityValidationForContainerConstaints.tar.gz)
`

**Comment by rfelcman** [comment]
Due a missing response I'm closing this issue now. Feel free to reopen this one or put there some comment if requested details are available.
