### ISSUE TITLE
remove org.eclipse.persistence.asm from the main build

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/eclipselink#1051]
The idea is to allow different project lifecycle for the `org.eclipse.persistence.asm` module from the one used by eclipselink itself.

Motivation:
 with current JDK release cadence, it is hard to catch up and provide new EclipseLink release everytime there is new JDK release just to accommodate new ASM to support it but in most cases, eclipselink as such is able to work with new ASM `as is`. There are rare cases when there are changes in eclipselink code required.

Proposed solution:
* remove `org.eclipse.persistence.asm` from `eclipselink.jar` all-in-one artifact
* create new release job(s) for the `org.eclipse.persistence.asm` artifact
* treat `org.eclipse.persistence.asm` as a regular project dependency (like ie `oracleddlparser`)
* relax OSGi imports for repackaged asm packages (basically remove upper boundary from the version range)
* let `eclipselink.jar` depend on the `org.eclipse.persistence.asm` artifact

Proposed Usage:
* default case: particular EclipseLink release depends on/uses latest available version of the `org.eclipse.persistence.asm` artifact
* usage on newly released JDK: new version of `org.eclipse.persistence.asm` is released. Users can explicitly define dependency on the new version of the `org.eclipse.persistence.asm` artifact (in maven) or put it on the classpath (ant, command-line) and keep using "old" version of EclipseLink till the new one is made available.

Probably key question, if we go this way, is where to put the source-code for the `org.eclipse.persistence.asm` artifact. I see 2 options:
1. keep in the main repository - we can create a job and keep going ourselves - this pattern is used ie in [jaxb-ri](https://github.com/eclipse-ee4j/jaxb-ri/tree/master/jaxb-ri) where some sub projects can be released when needed (ie codemodel or xsom), disadvantage can be seen in number of tags and tag naming
2. move it out to separate repository ie `eclipselink-asm` - this would require involvement of eclipse.org people who we would need to ask to set up the repo for us 

@dazey3 @jgrassel @rfelcman thoughts? This can be seen as incompatible change in service release wrt content of `eclipselink.jar` but I think this is something we may want to have in 2.7.9, not sure about 3.0.1 (it could probably wait for the release after it)

**Comment by jgrassel** [comment]
I agree, the cadence of new JDK and ASM releases has been rather disruptive.  We're still waiting for the CQ (https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23047) for ASM 9.1 to get through legal, and it's been sitting in limbo for a month with no reaction to repeated proddings for advancement.

Though much of the pain has been in the process - mainly Eclipselink legal, and then updating Eclipselink code.  All versions of Eclipselink require us to go through the codebase and change various ASM initializers to point to the latest version number, it's unfortunate that ASM doesn't simply have a constant which denotes the latest version instead of requiring users to specify a fixed version of ASM.  That would make ASM a lot more plug-and-playable.  With earlier versions of Eclipselink, we're still stuck manually repackaging and committing ASM source into the Eclipselink repository.  The fact that 3.0 got rid of that would be something worthwhile to repeat on earlier releases if managable.

However, because of the fixed version constant use in the code I'm not entirely sure I see what benefit splitting asm out of the `eclipselink.jar` all-in-one artifact, as it's still tightly coupled to a specific version of ASM.  Relaxing the upper version bounds sounds good to me, those are always going up, ASM is backwards compatible, so it seems like it's the floor value, rather than the ceiling value, which should be regularly updated anyways.

**Comment by lukasj** [comment]
> All versions of Eclipselink require us to go through the codebase and change various ASM initializers to point to the latest version number

I'm not sure this is really required. I haven't seen that code recently, so feel free to stop me/correct me if I'm wrong, but we should be updating the version of to be generated bytecode only when we are updating minimal Java SE version required by EclipseLink itself, shouldn't we? Even if not, I think - or better I hope - it should be possible to define some simple API between the library itself and EclipseLink core through which we could get what we need.

> I wonder if we should reevaluate the benefit of repackaging ASM like we do.

I've been thinking about this too. I can still see following two benefits of repackaging:
* we have full control over what we depend on (well, this is also disadvantage...) by defining our own packages which do not conflict with what is available in the environment
* think about JPMS - JDK itself contains some version of ASM but it does not (and it is very likely it is never going to) expose it to end users - be it apps or frameworks

**Comment by jgrassel** [comment]
It is, in order for the benefits of the newer level of ASM to be realized (presumably, this includes the support for newer JDK levels).  I'm talking about entries like this:

https://github.com/eclipse-ee4j/eclipselink/blob/30e95dba536019ff1e38c10d024abb53a6742431/jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataAsmFactory.java#L242-L252

Everytime we update ASM, for Eclipselink to gain the benefit of the update, the constant referenced by `super(Opcodes.ASM9)` also has to be updated to reflect the new version.  If we forget that, then updating the ASM library provides no benefit (aside from bugfixes.)

**Comment by lukasj** [comment]
> It would be nice if ASM added a LATEST constant

I see. We can introduce that in our repackaged version and update our code to refer to our new constant which in turn would refer to the latest opcode version from the ASM itself.

> ASM will reject class versions newer than what that version of the ASM library supports.

True, that is the default behaviour. But if our own reader [EclipseLinkClassReader](https://github.com/eclipse-ee4j/eclipselink/blob/master/plugins/org.eclipse.persistence.asm/src/main/java/org/eclipse/persistence/internal/libraries/asm/EclipseLinkClassReader.java#L32) is used, that check is already being bypassed...

**Comment by jgrassel** [comment]
> True, that is the default behaviour. But if our own reader [EclipseLinkClassReader](https://github.com/eclipse-ee4j/eclipselink/blob/master/plugins/org.eclipse.persistence.asm/src/main/java/org/eclipse/persistence/internal/libraries/asm/EclipseLinkClassReader.java#L32) is used, that check is already being bypassed...

I didn't realize that we had that in there.  Hmm.  I'm not entirely sure I'm comfortable with the class version unlock.  If all we used ASM for was for reading bytecode (say, for scanning annotations) it'd probably be okay, but with bytecode weaving we're going to get into trouble with new JVM bytecode operators and class constructs.  Hopefully users will heed the warnings emitted (just saw your update as I was typing this.)

**Comment by dazey3** [comment]
Is `eclipselink.jar` an OSGI bundle? 

Historically, I think this bundle has just been a generic JAR that is only meant for quick bootstrapping in development environments and SHOULD NOT BE USED in EE environments. Looking at the `eclipselink.jar` manifest, there aren't any requirements for importing versioned packages or anything really.

If `eclipselink.jar` were an OSGI bundle, couldn't we declare dependencies on ASM package versions as imports. We could then place `org.eclipse.persistence.internal.libraries.asm.EclipseLinkClassReader` in org.eclipse.persistence.core (or JPA) and eliminate the need for `org.eclipse.persistence.asm` to be it's own project?

**Comment by dazey3** [comment]
I guess I am just not sure why we pull in ASM, repackage it into `org.eclipse.persistence.asm.*` package names, bundle it into our own bundle (org.eclipse.persistence.asm), and ship it under an EclipseLink package name. That seems like a lot of work for something we can just list as a project dependency. Do we have a stipulation that we not have any hard dependencies on other projects?

Doesn't it make more sense to have a bundle dependency on ASM and include a package version import for the specific version EclipseLink currently supports?

org.eclipse.persistence.core\pom.xml:
```
<dependency>
    <groupId>org.ow2.asm</groupId>
    <artifactId>asm</artifactId>
    <version>9.0</version>
</dependency>
```

org.eclipse.persistence.core_qualifier.jar/META-INF/MANIFEST.MF:
```
Import-Package: ... org.objectweb.asm;version="9.0"; ...
```

Then we can import `org.objectweb.asm.ClassReader`.

**Comment by lukasj** [comment]
> This (the LATEST constant) seems like a feature which should be in the base ASM product itself.

ASM maintainers do not agree, see [317940](https://gitlab.ow2.org/asm/asm/-/issues/317940)
Our definition of `LATEST` should probably be rather `Math.min(SERuntime, ASM.MAX)` so our generated bytecode is the right one for the current environment.

> I'm not entirely sure I'm comfortable with the class version unlock.

The reader is there for annotation scanning and its main purpose is to give us time to upgrade ASM on our end and try to prevent issues like [429992](https://bugs.eclipse.org/bugs/show_bug.cgi?id=429992) or [532882](https://bugs.eclipse.org/bugs/show_bug.cgi?id=532882). The warning is there (and should stay there) to notify users about possible issues.

The same would be here with the benefit for us to be able to provide new version of the library itself right away without a need for brand new EclipseLink version. In most cases, it should just work even for some subset of already released EclipseLink versions (unless there are some backwards incompatible binary changes at the bytecode level) and we will still be testing it in up-to-date versions to see if any changes on eclipselink side itself would be needed. If so, we can just warn users that this or that may not work properly till new EclipseLink version is released.

> Is eclipselink.jar an OSGI bundle?

No, it is not OSGi bundle but there are people/appservers/customers using it - I do not personally like it but it is how it is. Not everything is based on OSGi, so the simple 'classpath' (or 'modulepath' going forward) use-case should be somehow supported too and that is also where one-jar approach makes sense - nobody wants to type x jars on the command line. Adding OSGi headers is not going to help here. What could work while still allowing us keeping `one-jar` approach could be an SPI between `core` and `asm` - not sure how much work would this be (and it will require repackaging already repackaged files to not have same package in two jars - not sure I like that).

> Doesn't it make more sense to have a bundle dependency on ASM and include a package version import for the specific version EclipseLink currently supports?

How is such resolution going to work in non-osgi environments? How is it going to work on JPMS should there be two versions of the library on the module path where it is not allowed for two jars to contain/export packages with the same name?

**Comment by jgrassel** [comment]
>ASM maintainers do not agree, see 317940

That's unfortunate that they've decided that is their position.

>Our definition of LATEST should probably be rather Math.min(SERuntime, ASM.MAX) so our generated bytecode is the right one for the current environment.

If ASM is not willing to introduce a LATEST constant, then I'm not sure how much benefit we get from adding our own.  It's still a hand-edit maintenance cost, just shifted from Eclipselink foundation/jpa code to the ASM code -- which with 2.6.* and 2.7.* means an additional hand edit after performing the various diff operations, after performing the package rename.

**Comment by lukasj** [comment]
> If ASM is not willing to introduce a LATEST constant, then I'm not sure how much benefit we get from adding our own. It's still a hand-edit maintenance cost, just shifted from Eclipselink foundation/jpa code to the ASM code -- which with 2.6.* and 2.7.* means an additional hand edit after performing the various diff operations, after performing the package rename.

not necessarily. If we introduce sth like `EclipseLinkClassVisitor` (abstract class/interface) in "our asm" and update current usages in jpa/moxy/dbws to extend/implement this new class/interface, I think we should be able to move most of the changes we currently have to do all over the codebase to just one place.

For example records - this introduces some new method in original ASM visitor. In our `EclipseLinkClassVisitor` this method will be implemented as no-op/skip. What we get in older versions is that we won't support records but we won't fail and we will be able to work properly as long as records (which we would ignore, probably with some warning) are not used in the code we are scanning. Similarly for the bytecode we generate - the one suitable for current environment will be provided. In theory, it should be possible to implement proper handling for records directly in our new class (I think this would be good gain); if not then specific handling would be needed directly in jpa/moxy/dbws and the next EclipseLink release. I think that is reasonable trade-off.

For 2.6.*/2.7.* - package names are not going to change, it is only the source of the jar/source jar which would be integrated there what I'm proposing to change - all supported versions would use the same version of our library (it would need to use the source level of 2.6); right now we are building 3 different versions, probably with different source/binary level, from same sources backported from one branch to another

**Comment by lukasj** [comment]
I have create 2 PRs to show how this could work going forward:

(master) #1054 - o.e.p.asm is removed from the main build to standalone maven project, added new ClassWriter which detects which bytecode version to use and generates code appropriate for current JVM, adopted ClassWriter through the eclipselink codebase, so it does not contain any JVM version specific code

(2.7) #1055 - removed repackaged asm sources from the branch, updated the build to use o.e.p.asm from maven central (currently the one built from master) and backported necessary new ClassWriter adoption related changes from master. With this change, further o.e.p.asm version updates/backports can be done by updating [one property](https://github.com/lukasj/eclipselink/blob/asm27/buildsystem/compdeps/pom.xml#L60) instead of dealing with backporting sources etc

**Comment by jgrassel** [comment]
This will make keeping up with the JDK update cadence much less painful.  Thank you, @lukasj, for pursing this.

**Comment by jgrassel** [comment]
I didn't notice this until today (when I looked inside the generated asm bundle), but I had thought that we were considering moving away from utilizing a version of ASM with renamed class packages (ie, the rename to `org.eclipse.persistence.internal.libraries.asm`, and just use ASM with the original `org.objectweb.asm` package name) as part of this effort.

**Comment by lukasj** [comment]
>  just use ASM with the original org.objectweb.asm package name

this would lead into situations when some other library brings different version of the original ASM into the environment and breaks us if its version is older then we need. Or we break that library if we bring in older version the other library needs. One can imagine that through maven dependency tree - if two dependencies depend on the same artifact with different version, the one closer to the main project  wins

**Comment by dazey3** [comment]
@lukasj 

Was there any consideration to moving the EclipseLink ASM code into its own repository? 

From my understanding, the strategy going forward is that each individual EclipseLink release (2.7, 3.0, master) will no longer import their respective build of EclipseLink ASM (2.7.9, 3.0.2, ect) but will instead pull in one shared version (for instance, `org.eclipse.persistence:org.eclipse.persistence.asm:9.1.0`)

I like this strategy. It is closer to importing the base ASM version and considering there is no EclipseLink release specific changes, I see no reason for each release branch to publish their own EclipseLink ASM bundle. However, the big problem I have with this strategy is that each EclipseLink release branch (2.6, 2.7, 3.0, master) still contains their own EclipseLink ASM source code. To me, it doesn't make much sense to have each release branch contain duplicate EclipseLink ASM code (more on this is a second), one branches version is built and published to maven central and all EclipseLink releases (2.7.9, 3.0.2) share that same build even though their branch might not have the same code checked in.

For me, I think it would make more sense to move the EclipseLink ASM code to a new repository so that it can be built and maintained separately. Then, each release branch can reference that artifact without it possibly being different from the code checked in.

Can this current strategy work? Of course. As long as every branch is kept manually in sync and up-to-date, then theoretically there shouldnt be a problem. However, this is an open source project so it would be fairly easy for this plan to fall apart. 

For instance, check in changes to the 2.7 branch for EclipseLink in support of ASM 9.2.0, build `org.eclipse.persistence:org.eclipse.persistence.asm:9.2.0` and upload to maven central. Then, update master, 2.6, and 2.7 to use the new `9.2.0`, but you forget to include the ASM code specific changes to each PR. Fast forward to ASM 9.3.0 update time. Are you going to remember you need to use the 2.7 branch to build the newest `org.eclipse.persistence:org.eclipse.persistence.asm:9.3.0`? It requires a lot of manual policing and control.

**Comment by lukasj** [comment]
@dazey3 

> Was there any consideration to moving the EclipseLink ASM code into its own repository?

at the end of the description of this issue, there is:

> Probably key question, if we go this way, is where to put the source-code for the org.eclipse.persistence.asm artifact. I see 2 options:

> keep in the main repository - we can create a job and keep going ourselves - this pattern is used ie in jaxb-ri where some sub projects can be released when needed (ie codemodel or xsom), disadvantage can be seen in number of tags and tag naming
> move it out to separate repository ie eclipselink-asm - this would require involvement of eclipse.org people who we would need to ask to set up the repo for us
> @dazey3 @jgrassel @rfelcman thoughts? 

Till today, there was no feedback on this. Should I have waited with moving this forward for ~5 months?

**Comment by dazey3** [comment]
@lukasj Oh, maybe I should have read the full description. Sorry!

**Comment by lukasj** [comment]
Agree that that 2.7.8->9.1.0 version number change is awful or not nice at least. Unfortunately I've found no better way to deal with a problem which appeared during the work on EclipseLink 3.0 coming from mismatch of OSGi bundle vs package version - in 2.x versions the pattern was that bundle version was equal to the eclipselink release version, so sth like 2.7.7 etc, while the version of exported package was set to repackaged asm version, so sth like 7.3.1 etc. When the build was changed to maven, we got both versions the same - bundle-version as well as the version of exported packages was set to 3.0.0 - so newer bundle was exporting older versions of packages and this could cause troubles in OSGi runtimes. One way to deal with this was to keep updating the package version manually - is error prone and complicates maintenance - or similar automatic approach with the same result; the other way was to come up with something else. That "else" is what we have now. The price which had to be paid was not so logical version bump you have noticed, but I think benefits we got and current ease of maintenance through multiple release streams outweighs it.

**Comment by dazey3** [comment]
I think the 2.7.8 -> 9.1.0 change is fine, but it did take me by surprise when 2.7.9 was failing and I had to dig into it. The change makes sense because if all release branches are going to use the same-ish releases of EclipseLink ASM, then they can't have 2.7.9, 3.0.2, ect. Using the ASM version of 9.x.x fits in ok as a major version change (it'd be worse to try rolling back to some kind of 1.x.x version) 

The first issue I had with it was that 3.0.2 was using the same 9.1.0 version... and I thought each release branch had it's own ASM files checked in! I hadnt remember that everything was reduced down to master now for building `org.eclipse.persistence:org.eclipse.persistence.asm`. I can move past that issue because we have all the duplicate code condensed down to just master. That's fine as a first step.

However, I think we could reopen the discussion now of moving it out of EclipseLink/master -> eclipse-ee4j/eclipselink-asm (or something like that). That would make the use of 9.x.x version make more sense since the repository can use it's own version independent of org.eclipse.persistence.

**Comment by lukasj** [comment]
@dazey3 

> I just want to now discuss moving what we have in eclipselink/master out to its own repo in https://github.com/eclipse-ee4j.

it may be good exercise to try to update ASM to 9.2 locally and/or through your local/private repo using both approaches to see what works better.

> However, I think we could reopen the discussion now of moving it out of EclipseLink/master -> eclipse-ee4j/eclipselink-asm (or something like that). That would make the use of 9.x.x version make more sense since the repository can use it's own version independent of org.eclipse.persistence.

Sure. As long as there is a volunteer who does the job and sets up testing part as well (GH action would be nice, Jenkins PR testing job would work too), then let's go for it :-)

**Comment by lukasj** [comment]
@dazey3 steps I have in mind and what I would do to update and test new asm on my local machine

* set version to 9.2.0-SNAPSHOT at https://github.com/eclipse-ee4j/eclipselink/blob/master/plugins/org.eclipse.persistence.asm/pom.xml#L30
* set version to 9.2 at https://github.com/eclipse-ee4j/eclipselink/blob/master/plugins/org.eclipse.persistence.asm/pom.xml#L89
* build the project using mvn -Poss-release -Dgpg.skip=true clean install
* set version to 9.2.0-SNAPSHOT at https://github.com/eclipse-ee4j/eclipselink/blob/master/pom.xml#L164
* build eclipselink using mvn -Poss-release -Dgpg.skip=true clean install; be it on a remote box, -Ptest-lrg should be used to kick off all moxy tests

…and that’s it

automating this would be the next step

**Comment by lukasj** [comment]
> Do you think it is acceptable to have ASM testing in https://github.com/eclipse-ee4j/eclipselink, separate from EclipseLink ASM source? I think it makes some sense to have a project contain some dependency testing to validate when a dependency is updated that it didn't break anything.

current PR verification job does that already. Basically when the PR to update o.e.p.asm bundle is created, this job in this repo runs current LRG tests. The thing is that once the asm bundle is taken from another repo, it should not be a SNAPSHOT build, it should be some release or pre-release build available in staging repository, so while having almost same tests being run in the new asm repo looks like overhead, it is actually not - one repo tests SNAPSHOT giving one early feedback, the other validates the final artifact
