### ISSUE TITLE
Bug 570702: Add support for Embeddable fields as JOIN targets

### ISSUE THREAD

**Issue by dazey3** [eclipse-ee4j/eclipselink#1058]
Linking to [BZ #570702](https://bugs.eclipse.org/bugs/show_bug.cgi?id=570702)

The JPA Spec, 4.4.4, defines two queries that it states are "equivalent":
```
In the following example, contactInfo denotes an embeddable class consisting of an address and set of phones. Phone is an entity.

SELECT p.vendor FROM Employee e JOIN e.contactInfo.phones p WHERE e.contactInfo.address.zipcode = '95054'

The following query is equivalent to the query above:

SELECT p.vendor FROM Employee e JOIN e.contactInfo c JOIN c.phones p WHERE e.contactInfo.address.zipcode = '95054'
```

First of all, the spec doesn't specifically define the Employee, ContactInfo, Address, and Phone classes for these queries. There are defined classes in other places of the JPA spec for Employee, ContactInfo, & Address but not for Phone. However, those defined Employee, ContactInfo, & Address classes do not match the attributes defined in this query. For this reason, I am using the following ORM classes that at least follow the definition described in 4.4.4 and 4.4.5.1

```
    @Entity
    public class Employee {
        @Id int id;
        @Embedded private ContactInfo contactInfo;
    }

    @Entity
    public class Phone {
        @Id private int id;
        private String vendor;
    }

    @Embeddable
    public class ContactInfo {
        @Embedded private Address address;
        @ManyToMany private List<Phone> phones;
    }

    @Embeddable
    public class Address {
        private String street;
        private String city;
        private String state;
        private String zipcode;
    }
```

Running both of these "equivalent" queries against EclipseLink, the second query fails with the following exception:
```
Caused by: Exception [EclipseLink-0] (Eclipse Persistence Services - 2.6.8.WAS): org.eclipse.persistence.exceptions.JPQLException
Exception Description: Problem compiling [SELECT e FROM Employee e JOIN e.contactInfo c JOIN c.phones p]. 
[30, 43] The collection-valued path 'e.contactInfo' must resolve to an association field.
	at org.eclipse.persistence.internal.jpa.jpql.HermesParser.buildException(HermesParser.java:155)
	at org.eclipse.persistence.internal.jpa.jpql.HermesParser.validate(HermesParser.java:347)
	at org.eclipse.persistence.internal.jpa.jpql.HermesParser.populateQueryImp(HermesParser.java:278)
	at org.eclipse.persistence.internal.jpa.jpql.HermesParser.buildQuery(HermesParser.java:163)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.buildEJBQLDatabaseQuery(EJBQueryImpl.java:142)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.buildEJBQLDatabaseQuery(EJBQueryImpl.java:116)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.<init>(EJBQueryImpl.java:102)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.<init>(EJBQueryImpl.java:86)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.createQuery(EntityManagerImpl.java:1618)
	... 24 more
```

EclipseLink is very specifically throwing this exception because it has coded that a JOIN against an AggregateMapping is not allowed (org.eclipse.persistence.jpa.jpql.AbstractSemanticValidator.validateCollectionValuedPathExpression). EclipseLink expects only CollectionMappings (org.eclipse.persistence.mappings.CollectionMapping)and RelationshipMapping (ForeignReferenceMapping, AbstractCompositeCollectionMapping, AbstractCompositeDirectCollectionMapping) in JOIN expressions. 

Reading more into the JPA Spec, I don't see anywhere where it expressly supports JOINs against Embeddable (and therefore basic) fields. Is it the JPA Spec that is wrong here and should be fixed? Or is it EclipseLink that should be allowing JOINs against AggregateObjectMappings?

Just one more data point is that I altered EclipseLink locally to allow for AggregateMappings by altering the validation in org.eclipse.persistence.jpa.jpql.AbstractSemanticValidator.validateCollectionValuedPathExpression and both queries execute the same. There may be additional ramifications of this change that I need to checkout, but at least in this case it only seems that EclipseLink forbids this function and the query can be constructed fine.

**Comment by jgrassel** [comment]
Can you put a copy of the issue's text here, instead of just linking to BugZilla?  It makes Eclipselink's github easier to search for issues, and you never know, one day the Eclipse foundation's BugZilla might go away.

**Comment by dazey3** [comment]
I was leaning towards this being a JPA Specification issue and that EclipseLink may be in the right here, but reading how a JOIN is defined in the JPA Spec BNF, now I think that maybe EclipseLink should be allowing JOINs on AggregateMappings:

```
join ::= join_spec join_association_path_expression [AS] identification_variable
[join_condition]

join_spec::= [ LEFT [OUTER] | INNER ] JOIN

join_association_path_expression ::=
    join_collection_valued_path_expression |
    join_single_valued_path_expression

join_collection_valued_path_expression::= 
    identification_variable.{single_valued_embeddable_object_field.}*collection_valued_field

join_single_valued_path_expression::=
    identification_variable.{single_valued_embeddable_object_field.}*single_valued_object_field
```

And Section 4.4.4.1 defines 'single_valued_object_field':
```
A single_valued_object_field is designated by the name of an association field in a one-to-one or
many-to-one relationship or a field of embeddable class type. The type of a
single_valued_object_field is the abstract schema type of the related entity or embeddable class.
```

Granted, 'single_valued_embeddable_object_field' is not defined in the spec, which seems like a problem to me... but, thankfully, 'single_valued_object_field' IS defined. Interestingly, 'single_valued_object_field' seems to be defined to allow embeddable class types!

If I am reading this BNF correctly, this should allow something like:
```
SELECT p.vendor FROM Employee e JOIN e.contactInfo c
```
Where 'e' is the 'identification_variable' and 'contactInfo' is the 'single_valued_object_field', correct?
