### ISSUE TITLE
Bug 573094: TRIM function generates incorrect SQL for CriteriaBuilder

### ISSUE THREAD

**Issue by dazey3** [eclipse-ee4j/eclipselink#1084]
Linking to [BZ #573094](https://bugs.eclipse.org/bugs/show_bug.cgi?id=573094)

EclipseLink generates bad SQL from CriteriaBuilder for the trim(Character, String) function.

Entities:
```java 
@Entity
public class SimpleEntity {
    @Id private long id;

    private String strVal1;
}
```
```java 
@StaticMetamodel(SimpleEntity.class)
public class SimpleEntity_ {
    public static volatile SingularAttribute<SimpleEntity, Long> id;
    public static volatile SingularAttribute<SimpleEntity, String> strVal1;
}
```

Test:
```java 
    CriteriaBuilder cb = em.getCriteriaBuilder();
    CriteriaQuery<Object[]> cquery = cb.createQuery(Object[].class);
    Root<SimpleEntity> root = cquery.from(SimpleEntity.class);
    cquery.multiselect(cb.trim(cb.literal('A'), cb.literal("AAHELLO WORDAAAAA")));
    cquery.where(cb.equal(root.get(SimpleEntity_.strVal1), cb.literal("HELLO")));

    Query query = em.createQuery(cquery).getResultList();
```

Generated SQL:
```
    SELECT TRIM('AAHELLO WORDAAAAA' FROM 'AAHELLO WORDAAAAA') FROM SIMPLEENTITY WHERE (STRVAL1 = 'HELLO')
```

This is obviously very wrong. EclipseLink ignores the Character value and prints the String value twice in its stead. Its a bit frustrating though because not all databases fail executing this query! So some applications might currently be running this bad query with no failures and just bad results. Even so, the behavior is so blatantly wrong and obvious that perhaps fixing this without requiring a gating property, to allow users to undo the behavior change, is fine.

**Comment by dazey3** [comment]
Looking into this closer, it seems that the Trim with (Character, String) doesn't work on many platforms!

Example:
```java
    CriteriaBuilder cb = em.getCriteriaBuilder();
    CriteriaQuery<Object[]> cquery = cb.createQuery(Object[].class);
    Root<SimpleEntity> root = cquery.from(SimpleEntity.class);
    cquery.multiselect(root.get(SimpleEntity_.strVal1));
    cquery.where(cb.equal(root.get(SimpleEntity_.strVal1), cb.trim(cb.literal('A'), cb.literal("AAHELLO WORDAAAAA"))));

    Query query = em.createQuery(cquery).getResultList();
```

SQL - ORACLE:
```
SELECT STRVAL1 FROM SIMPLEENTITY WHERE (STRVAL1 = TRIM(? FROM ?))
	bind => [AAHELLO WORDAAAAA, A]
```

I think the issue is rather complex. Looking at the DatabasePlatform classes, DB2Platform, MySQLPlatform, and SymfowarePlatform all override and implement their own Trim ExpressionOperators! And these platforms seem to work just fine because they reorder the the indices:
```
    int[] indices = {1, 0};
    exOperator.setArgumentIndices(indices);
```

I think that these platforms were "fixed", but other platforms like Oracle, Informix, Postgres weren't. I think the correct fix would be to make these indices the default for all trim functions.

**Comment by dazey3** [comment]
Here is the issue:

`org.eclipse.persistence.internal.expressions.BaseExpression`'s have a baseExpression attribute:
```java
    /** The base expression is what this was derived from. */
    protected Expression baseExpression;
```

When calling `org.eclipse.persistence.internal.jpa.querydef.CriteriaBuilderImpl`, an Expression is created and the baseExpression is set. For every function (that I looked at) the baseExpression is set as the FIRST argument. HOWEVER, for Trim2, LTrim2, and RTrim2, which are the TRIM functions that take a CHAR argument first, the baseExpression is set as the SECOND argument, the String.

```java
public Expression<String> trim(Expression<Character> t, Expression<String> x){
    List list = this.buildList(x, t);
    return new FunctionExpressionImpl(this.metamodel, ClassConstants.STRING, ((InternalSelection)x).getCurrentNode().trim(((InternalSelection)t).getCurrentNode()), list, "trim");
    }
```
Notice that the List is inverted! Now, interestingly enough, I think this actually makes sense. The normal Trim, LTrim, and RTrim functions, which only have 1 argument, have their baseExpression set as the String argument. Makes sense to me that Trim2, LTrim2, and RTrim2 should also.

The problem comes in with this code:
`org.eclipse.persistence.internal.expressions.FunctionExpression.rebuildOn(Expression newBase)`:
```java 
    Expression newLocalBase = getBaseExpression().rebuildOn(newBase);
    Vector newChildren = org.eclipse.persistence.internal.helper.NonSynchronizedVector.newInstance(this.children.size());
    for (int i = 1; i < this.children.size(); i++) {// Skip the first one, since it's also the base
        newChildren.addElement(((Expression)children.elementAt(i)).rebuildOn(newBase));
    }
    newLocalBase.setSelectIfOrderedBy(getBaseExpression().selectIfOrderedBy());
    FunctionExpression rebuilt = (FunctionExpression) newLocalBase.performOperator(this.operator, newChildren);
```
Notice that the loop through the children skips the first one! There is even a comment in the code that says "Skip the first one, since it's also the base". Except, for our Trim2 function, THE CHARACTER ARGUMENT is first, not the STRING argument. Meaning the Character argument is skipped and later code just fills in the blank with 2 String arguments...

Digging even deeper, we can see WHY the Character argument is first:
`org.eclipse.persistence.expressions.Expression.trim(Object substring)`:
```java 
public Expression trim(Object substring) {
    ExpressionOperator anOperator = getOperator(ExpressionOperator.Trim2);
    return anOperator.expressionForWithBaseLast(this, substring);
}
```
This is the ONLY function that makes use of `expressionForWithBaseLast()`. The whole point of this function is to place the expressionBase at the END of the children list, instead of the front like every other function. This completely contradicts the code, and comment, in `org.eclipse.persistence.internal.expressions.FunctionExpression.rebuildOn()`.

**Comment by dazey3** [comment]
Something interesting I found in the code is a comment in `org.eclipse.persistence.expressions.ExpressionOperator.rightTrim2()`:
```java 
    // bug 2916893 rightTrim(substring) broken
```

Does anyone know what this is a reference to? It doesn't look like a bugs.eclipse.org bug since those are 6 digits. Perhaps an old TopLink bug number? I don't know how to access any of those to determine what that issue was. Curious.

**Comment by lukasj** [comment]
> // bug 2916893 rightTrim(substring) broken

ouch, you're watching a comment which is celebrating 18th birthday this week! Wanna drink? :-)

The issue there was that `builder.get("firstName").rightTrim("b").equal("Bo");` produced
wrong `SELECT ... FROM EMPLOYEE t0 ... WHERE ((RTRIM(t0.F_NAME)'b' = 'Bo') ...)` instead of
correct `SELECT ... FROM EMPLOYEE t0 ... WHERE ((RTRIM(t0.F_NAME, 'b') = 'Bo') ...)`

At that time Expressions were able to accept only fixed number of arguments while corresponding SQL functions could accept a variable number of arguments. Important note is that `RightTrim2` is supposed to be the same as `RightTrim` but taking 2 arguments instead of 1.

tests which were added with this `FeatureTestModel/ExpressionUnitTestSuite/RightTrim$StringTest` and/or `ExpressionTests.ExpressionUnitTestSuite#_addRightTrim$StringTest`.

...not sure this helps...

**Comment by dazey3** [comment]
Hmm, I think the fix for this may be incorrect after re-reviewing the documentation for LTRIM and RTRIM for DB2 and Oracle...

I had misread the documentation before and inverted the arguments for standard LTRIM and RTRIM. Though in my defense, it doesnt help when the documentation names the first argument "char", but then describes it as "LTRIM removes from the left end of char all of the characters contained in set". I equated the `TRIM(LEADING char FROM string)` function to `LTRIM(char, string)`. I need to fix this properly in a new PR
