### ISSUE TITLE
Eclipselink uses select @@IDENTITY instead of scope_identity() for target platform SQL server to populate the primary key of inserted record

### ISSUE THREAD

**Issue by shankuljain** [eclipse-ee4j/eclipselink#1218]
Re-reporting the bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=288015 which hasn't been addressed in last 12 years. 

Check below SO post to first understand the difference between `select @@IDENTITY` and `scope_identity()`
https://stackoverflow.com/questions/1920558/what-is-the-difference-between-scope-identity-identity-identity-and-ide/1920640#1920640

Note that this is specific to SQL server platform.

Now, if there is an insert trigger which inserts entry into another table which also have the auto-incremented primary key, it will return the primary key from the table where the trigger made an insert. This auto-increment primary key might be out of sync with the target table and hence result in incorrect population of Primary key in entity class.

**Comment by shankuljain** [comment]
Some relevant discussions:

1. https://www.eclipse.org/forums/index.php/t/1099931/ 
2. http://eclipse.1072660.n5.nabble.com/How-to-configure-buildSelectQueryForIdentity-td6111.html 
3. https://stackoverflow.com/questions/26767180/eclipselink-record-insert-returns-wrong-id

**Comment by shankuljain** [comment]
T-SQL doc: https://docs.microsoft.com/en-us/sql/t-sql/functions/identity-transact-sql?view=sql-server-ver15#remarks

**Comment by dazey3** [comment]
see #1480
