### ISSUE TITLE
Problem with building with maven 3.8.2

### ISSUE THREAD

**Issue by pzygielo** [eclipse-ee4j/eclipselink#1242]
Since maven 3.8.2 (which includes https://github.com/apache/maven/commit/5a8997312680a4b9c69a129801524691bc546c08 that I think is the cause of change) the EL can no longer be built due to [directory-maven-plugin](https://github.com/jdcasey/directory-maven-plugin) not being compatible (and BTW probably dead anyway).

It results with:
```
[ERROR] Failed to execute goal org.commonjava.maven.plugins:directory-maven-plugin:0.3.1:highest-basedir (find-project-root) on project org.eclipse.persistence.parent: Cannot find a single highest directory for this project set. First two candidates directories don't share a common root. -> [Help 1]
```

As maven versions are not specified exactly in 
https://github.com/eclipse-ee4j/eclipselink/blob/c0f808e3204abeafeaf9c63e69b16d0e0f75571f/.github/workflows/codeql-analysis.yml#L57  or in https://github.com/eclipse-ee4j/eclipselink/blob/c0f808e3204abeafeaf9c63e69b16d0e0f75571f/etc/jenkins/pr_verify.groovy#L94 they might be upgraded out of control of this project.

Please consider taking action before that happens.

**Comment by michael-o** [comment]
Do you consider this to be a regression or just surfaced a bug in the mentioned plugin?

**Comment by pzygielo** [comment]
> Do you consider this to be a regression or just surfaced a bug in the mentioned plugin?

As [MNG-7170](https://issues.apache.org/jira/browse/MNG-7170) is classified as improvement, I'd think that this is regression in maven, unexpected in microrelease (3.8.1 to 3.8.2). 

[maven-3.8.2](https://issues.apache.org/jira/projects/MNG/versions/12349965) declares
> Fixes and non-invasive backports from Maven 4.0.0-alpha-1.

I have not investigated the plugin itself, so have no idea what happens [there](https://github.com/jdcasey/directory-maven-plugin/blob/directory-maven-plugin-0.3.1/src/main/java/org/commonjava/maven/plugins/execroot/HighestBasedirGoal.java#L110-L124) to result with:
```
Caused by: org.apache.maven.plugin.MojoExecutionException: Cannot find a single highest directory for this project set. First two candidates directories don't share a common root.
    at org.commonjava.maven.plugins.execroot.HighestBasedirGoal.findDirectory (HighestBasedirGoal.java:121)
    at org.commonjava.maven.plugins.execroot.AbstractDirectoryGoal.execute (AbstractDirectoryGoal.java:80)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
```
But this works with 3.8.1 and it doesn't break the build.

Nothing related seems to be mentioned in [known-issues](https://maven.apache.org/docs/3.8.2/release-notes.html#known-issues) yet.

**Comment by michael-o** [comment]
It could be a regression, but also just a bug in the plugin. @jdcasey, can you help out on your plugin? @mickaelistria any idea?

@pzygielo Then this plugin will be broken on Maven 4 as well. Reverting just fix the symptom, not the root cause.

**Comment by pzygielo** [comment]
> I have not investigated the plugin itself, so have no idea what happens [there](https://github.com/jdcasey/directory-maven-plugin/blob/directory-maven-plugin-0.3.1/src/main/java/org/commonjava/maven/plugins/execroot/HighestBasedirGoal.java#L110-L124) 

With 3.8.1 `files` has only one element - current project.
With 3.8.2 `files` contains additionally parent.

I think the plugin [has problem](https://github.com/jdcasey/directory-maven-plugin/blob/cd432cfab79dc9ea0801980e9e6a44729c4b518d/src/main/java/org/commonjava/maven/plugins/execroot/HighestBasedirGoal.java#L80) with recognizing parent now, as parent has not-null basedir.

```
stop at org.commonjava.maven.plugins.execroot.HighestBasedirGoal:80
monitor print p
monitor print p.getBasedir()
```

**Comment by michael-o** [comment]
So you are saying it retrieves the wrong value?

**Comment by mickaelistria** [comment]
I think `p.getBasedir() == null` is erroneously used in order to check whether p is a resolved parent. I am not aware of anything in Maven that implies such assumption; so it seems to me the building is built on a non-specified side-effect, that changed in the meantime.

**Comment by michael-o** [comment]
> 
> 
> I think `p.getBasedir() == null` is erroneously used in order to check whether p is a resolved parent. I am not aware of anything in Maven that implies such assumption; so it seems to me the building is built on a non-specified side-effect, that changed in the meantime.

Thanks for the info! @pzygielo Can you locally drop this assumption and see whether the plugin works?

**Comment by rfelcman** [comment]
I tried to replace `org.commonjava.maven.plugins:directory-maven-plugin:0.3.1` with following (additional debug comments there) but same issue with Maven 3.8.2:
        
```
          <plugin>
                <groupId>org.codehaus.gmaven</groupId>
                <artifactId>groovy-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>find-project-root</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>execute</goal>
                        </goals>
                        <configuration>
                            <source>
                                <![CDATA[
                                def rootPom = project;
                                log.info("Current project parent [rootPom.parent]:  " + rootPom.parent);
                                log.info("Current project parent basedir [rootPom.parent.basedir]:  " + rootPom.parent.basedir);
                                while (rootPom.parent.basedir != null) {
                                    log.info("Current project [rootPom]:  " + rootPom);
                                    log.info("Current project basedir [rootPom.basedir]:  " + rootPom.basedir);
                                    log.info("parent project [rootPom.parent]:  " + rootPom.parent);
                                    log.info("parent project basedir [rootPom.parent.basedir]:  " + rootPom.parent.basedir);
                                    rootPom = rootPom.parent;
                                }
                                project.properties.setProperty("project.root.location", rootPom.basedir.toString());
                                log.info("EclipseLink Parent project directory [project.root.location]:  " + project.properties['project.root.location']);
                                log.info("Topmost parent directory [rootPom.basedir]:  " + rootPom.basedir);
                                ]]>
                            </source>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by michael-o** [comment]
https://issues.apache.org/jira/browse/MNG-7215
