### ISSUE TITLE
Cannot create a custom ID generator

### ISSUE THREAD

**Issue by webhsw** [eclipse-ee4j/eclipselink#1342]
A custom id-generator like https://wiki.eclipse.org/EclipseLink/Examples/JPA/CustomSequencing cannot created in version 3.1.0 M1 because org.eclipse.persistence.internal.databaseaccess.Accessor and org.eclipse.persistence.internal.sessions.AbstractSession are not exported in module-info.

**Comment by rfelcman** [comment]
As there is no any response, I think, that bug is fixed in the mentioned versions. I'm closing this bug now. If You feel, that bug remains please leave message here or reopen this bug.
