### ISSUE TITLE
Cannot set FOR UPDATE in conjunction with ORDER BY and / or LIMIT (OracleDB & Derby)

### ISSUE THREAD

**Issue by mrakorcl** [eclipse-ee4j/eclipselink#1369]
Running against OracleDB or Derby, if ORDER BY is set on CriteriaQuery, and / or setMaxResults is called on TypedQuery object, then a lock instruction applied using

```
final TypedQuery<Long> query = em.createQuery(cq);
query.setLockMode(LockModeType.PESSIMISTIC_WRITE);
```
results in syntax error on OracleDB, while against Derby the instruction appears to be ignored. Running against SQLServer this works as expected.

Using `query.unwrap(JpaQuery.class).getDatabaseQuery().getSQLString()` to obtain the resultant SQL statement.

Running the following:
```
            cq.orderBy( cb.asc( jpaTable.get(JPATABLE_.getId()) ) );
            final TypedQuery<Long> query = em.createQuery(cq);
            query.setMaxResults(pageSize);
            query.setLockMode(LockModeType.PESSIMISTIC_WRITE);
            final List<Long> ids = query.getResultList();
```
Although the row limit doesn't appear to be applied in the SQL statement, it is enforced somehow, because we do get correct result: `SELECT ID FROM JPATABLE WITH (UPDLOCK) WHERE (TENANT = ?) ORDER BY ID ASC`

Against Derby, the FOR UPDATE instruction seems to be ignored - `SELECT ID AS a1 FROM JPATABLE WHERE (TENANT = ?) ORDER BY ID ASC OFFSET ? ROWS FETCH NEXT ? ROWS ONLY`

Against OracleDB, this results in an exception:
    _javax.persistence.PessimisticLockException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.8.v20201217-ecdf3c32c4): org.eclipse.persistence.exceptions.DatabaseException
    Internal Exception: java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended
    Error Code: 933_

Running a query with row limit and ORDER BY, but with no locking specified works correct against all DB types. Running a query with locking specified, and without ORDER BY and row limit also works fine.

**Comment by rfelcman** [comment]
It's related with following bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=453208
