### ISSUE TITLE
Release 4.0.0-M1 for testing?

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/eclipselink#1371]
I'm working on GlassFish 7 and would love to try to integrate an early build of 4.0.0. 

With 3.1.0-M1 there are errors like the following:

```
Unable to resolve
    org.eclipse.persistence.moxy [247]
    missing requirement
        &(package = jakarta.xml.bind) (version >= 3.0.0) (!(version >= 4.0.0))
```

**Comment by lukasj** [comment]
this needs jaxb 4; jaxb 4 is going to break metro, so this needs metro, there are dependencies one needs to work through to make this happen

**Comment by lukasj** [comment]
one should probably [draw a graph](https://github.com/eclipse-ee4j/metro-wsit/blob/master/etc/metro-dependencies.md)...

**Comment by arjantijms** [comment]
Recently one just like that was done for the web profile. For GlassFish its difficult to keep it readable in one graph, especially as there are the API dependencies and the impl dependencies.

**Comment by lukasj** [comment]
@rfelcman close this once there is 4.0.0-M1 available, so @arjantijms knows about it. Thx!

**Comment by rfelcman** [comment]
Hello,
4.0.0-M1 is in Jakarta staging repository. See https://jakarta.oss.sonatype.org/content/groups/staging/org/eclipse/persistence/eclipselink/4.0.0-M1/
