### ISSUE TITLE
duplicate persistence classes in classpath

### ISSUE THREAD

**Issue by mebigfatguy** [eclipse-ee4j/eclipselink#1406]
Greetings,

As my application includes

eclipselink 2.7.10
jakarta.persistence 2.2.3

Jetty dumps tons and tons of warnings about duplicate classes, such as

javax.persistence.Access scanned from multiple locations: jar:file:///tmp/jetty-0_0_0_0-8080-acmems_war-_acmems-any-6763641951174072661/webapp/WEB-INF/lib/eclipselink.jar!/javax/persistence/Access.class, jar:file:///tmp/jetty-0_0_0_0-8080-acmems_war-_acmems-any-6763641951174072661/webapp/WEB-INF/lib/jakarta.persistence.jar!/javax/persistence/Access.class

Which begs the question, if eclipselink depends on jakarta.persistence, why does eclipselink have all these classes defined in its jar when they are in jakarta.persistence?

Shouldn't these classes be removed from eclipselink?

There are ~70 classes that spam the logs every time it starts.

Or am i confused about what's going on, or how i'm supposed to be using these jars, somehow?

**Comment by rfelcman** [comment]
There are following reasons why JPA API is packaged into `eclipselink.jar` bundle:

- Ensure JPA API 2.0 is available (backward compatibility) e.g. for WebLogic Server see https://bugs.eclipse.org/bugs/show_bug.cgi?id=525457#c5
- Historical/compatibility reasons. I can't say exact date when this kind of bundle started, but it exists at least 10 years.
- Make EclipseLink more friendly in JSE env to distribute bundle where everything (Core, JPA, MOXy (JAXB-IMPL), SDO...) is available in single jar.

If You want use EclipseLink without attached JPA API please use individual artifacts see https://search.maven.org/search?q=org.eclipse.persistence

**Comment by mebigfatguy** [comment]
Ok, but unfortunately eclipselink isn't complete.

Thanks, i'll try looking at the individual artifacts
