### ISSUE TITLE
Bug 579327: ParameterExpression in CriteriaBuilder.isNull() doesn't register

### ISSUE THREAD

**Issue by dazey3** [eclipse-ee4j/eclipselink#1457]
Linking to [BZ #579327](https://bugs.eclipse.org/bugs/show_bug.cgi?id=579327)

Passing a ParameterExpression to CriteriaBuilder.isNull() results in an exception when setting the ParameterExpression value on the Query.

Test:
```
    CriteriaBuilder cb = em.getCriteriaBuilder();
    CriteriaQuery<Integer[]> cquery = cb.createQuery(Integer[].class);
    Root<SimpleEntity> root = cquery.from(SimpleEntity.class);
    cquery.multiselect(root.get(SimpleEntity_.intVal1));

    ParameterExpression<String> strParam1 = cb.parameter(String.class);
    cquery.where(cb.isNull(strParam1));

    Query query = em.createQuery(cquery);
    query.setParameter(strParam1, "HELLO");
    query.getResultList();
```

Exception:
```
java.lang.IllegalArgumentException: No parameter with name : Parameter[name=null] was found within the query: ReportQuery(referenceClass=SimpleEntity ).
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.setParameter(EJBQueryImpl.java:548)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.setParameter(EJBQueryImpl.java:1)
```

**Comment by rfelcman** [comment]
Sorry but, there are some test errors in continues builds (Derby DB) see:
https://ci.eclipse.org/eclipselink/job/eclipselink-cb-master/lastCompletedBuild/testReport/
https://ci.eclipse.org/eclipselink/job/eclipselink-cb-3.0/152/
I think, that in 2.7 too, but JPA.JSE are not executed in continues builds.

**Comment by dazey3** [comment]
@rfelcman 

Thanks for letting me know! It seems that one of my tests is invalid for Derby and I need to account for that.

```
SELECT ITEM_STRING1 FROM SIMPLE_TBL01 WHERE (NULL IS NOT NULL)
```
This query works on Oracle, DB2, SQLServer, Postgres. But it fails on Derby and I missed that. It seems to be illegal.
