### ISSUE TITLE
Need to update JPQLGrammar for JPA 2.2 and 3.0

### ISSUE THREAD

**Issue by lak-proddev** [eclipse-ee4j/eclipselink#1474]
Eclipse DALI project uses the plugin "org.eclipse.persistence.jpa.jpql" . which has the grammar definitions.
There is no update for JPA 2.2 and 3.0 in the latest version (3.0.2 )jpql plugin.

DALI is going to add the new JPA 3.0 support. It requires the new definitions. I requesting to add it in next release.

Correct me if anything missing.

Thanks

**Comment by lukasj** [comment]
artifact(s) from maven central - https://repo1.maven.org/maven2/org/eclipse/persistence/org.eclipse.persistence.jpa.jpql/ - cannot be used? what are they missing?

**Comment by lak-proddev** [comment]
Maven artifacts are fine.
There are JPQL Grammar classes separately for each JPA version. and EclipseLink  
> org.eclipse.persistence.jpa.jpql.parser.JPQLGrammar2_1 extends org.eclipse.persistence.jpa.jpql.parser.AbstractJPQLGrammar 

We need the updated classes for JPA 2.2, JPA 3.0  and above EclipseLink 2.7 versions.

**Comment by lukasj** [comment]
Tome, take a look at this

**Comment by Tomas-Kraus** [comment]
OK, added to my TODO list.

**Comment by lukasj** [comment]
there is no reason to close this - grammar in 3.1 was changed and if DALI wants to provide support for jakarta namespace, it simply needs new version anyway

**Comment by lukasj** [comment]
It is NOT about providing support through EclipseLink 2.6.x release, it is about providing new release with the new feature

**Comment by dazey3** [comment]
> In that case, We can close it and can continue with the existing jpql jar used in DALi.

Certainly, DALi can use the appropriate `org.eclipse.persistence.jpa.jpql` bundle, depending on the JPA level, and should not just continue using the EclipseLink 2.6 `org.eclipse.persistence.jpa.jpql` bundle:
```
    org.eclipse.persistence.jpa.jpql-2.7.10.jar -> JPA 2.2
    org.eclipse.persistence.jpa.jpql-3.0.2.jar - > JPA 3.0
```

Whatever process DALi has that specifically uses the `org.eclipse.persistence.jpa.jpql.parser.JPQLGrammar2_1` class can continue using that class for JPA 2.2 and JPA 3.0.

> there is no reason to close this - grammar in 3.1 was changed and if DALI wants to provide support for jakarta namespace, it simply needs new version anyway

Agreed! I'm not sure what JPQL BNF changes there were in JPA 3.1, but if there are some, we should create a new `org.eclipse.persistence.jpa.jpql.parser.JPQLGrammar3_1`.

Also, at that time, if we want to create `org.eclipse.persistence.jpa.jpql.parser.JPQLGrammar2_2` and `org.eclipse.persistence.jpa.jpql.parser.JPQLGrammar3_0` empty classes for completeness sake, that sounds fine.

**Comment by lak-proddev** [comment]
Okay, Sure.

Actually, this is the immediate requirement to update the jar's to 3.x
https://github.com/eclipse-ee4j/eclipselink/issues/1387
If anyone can look into it, it will be helpful us.

**Comment by lak-proddev** [comment]
This also another blocker because of unsigned jars.
https://github.com/eclipse-ee4j/eclipselink/issues/507

**Comment by lukasj** [comment]
How is that solved for 3rd party/non-eclipse-owned dependencies?

**Comment by Tomas-Kraus** [comment]
Work is in progress in PR #1491

**Comment by Tomas-Kraus** [comment]
Work is in progress in PR #1491
