### ISSUE TITLE
EXTRACT() on YEAR returns BigDecimal type on Postgres

### ISSUE THREAD

**Issue by jgrassel** [eclipse-ee4j/eclipselink#1574]
The spec is clear about the return type for EXTRACT(YEAR):

```
For the following field type identifiers, EXTRACT returns an integer value:
• YEAR means the calendar year.
```

However, the following code when run with Postgres database:
``
        // Verify EXTRACT(YEAR) from a LocalDate field
        q = em.createQuery("SELECT EXTRACT(YEAR FROM qdte.localDateData) FROM QueryDateTimeEntity qdte WHERE qdte.id = 1");
        result = q.getSingleResult();
        Assert.assertNotNull(result);
        System.out.println("OL_JAG: " + result + " / " + result.getClass());
        Assert.assertEquals(2022, result);
```

Fails the unit test with `expected:<2022> but was:<2022> `, however, the type returned is a BigDecimal, not an integer, which is why the assertion failed (looking at debug produced in the log file):

```
OL_JAG: 2022 / class java.math.BigDecimal
```

**Comment by jgrassel** [comment]
Further testing indicates that this affects all extract options on postgres, not just year.

**Comment by Tomas-Kraus** [comment]
This must be coming from the DB engine. You did not use TypedQuery so no number conversion was done.
I made EclipseLink tests based on `TypedQuery<Number>` and I'm using `long y = q.getSingleResult().longValue();` to read returned value. This was passing for Postgress too.

Anyway, JPA spec contains following definbition:

For the following field type identifiers, EXTRACT returns an integer value:
 - YEAR means the calendar year.

So I'll modify EXTRACT operator in Postgres platform to return integer.

**Comment by Tomas-Kraus** [comment]
Just to confirm the issue, I put breakpoint into existing test:
```
    @Test
    public void testIssue1539LocalDate() {
        final EntityManager em = emf.createEntityManager();
        try {
            em.getTransaction().begin();
            // Record with ID = 1 contains year 2022
            TypedQuery<Number> query = em.createQuery("SELECT EXTRACT(YEAR FROM qdte.dateValue) FROM DateTimeQueryEntity qdte WHERE qdte.id = 1", Number.class);
            Number year = query.getSingleResult();
            em.getTransaction().commit();
            // Check returned year value
            MatcherAssert.assertThat(year.intValue(), Matchers.equalTo(2022));
        } catch (Throwable t) {
            t.printStackTrace();
            throw t;
        } finally {
            if (em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            em.close();
        }
    }
```
and yes, value of `year` is of the BigDecimal type.

**Comment by Tomas-Kraus** [comment]
I can solve it using `CAST(EXTRACT YEAR FROM qdte.dateValue) AS INTEGER)` for everything except SECOND which will be cast as FLOAT.

**Comment by Tomas-Kraus** [comment]
It's resolved in JPQL parser now. No additional casts on EXTRACT() are needed in Platforms.
