### ISSUE TITLE
ceiling,floor, round methods in Criteria API caculate wrong results

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/eclipselink#1593]
Glassfish 7.0.0-M7 + Built-in Derby Database
Java 17
Windows 10

I have tried to refresh my [JPA 3.1 examples](https://github.com/hantsy/jakartaee10-sandbox/tree/master/jpa) and test functionalities against the newest Glassfish 7.0.0 M7. 

Unfortunately the numeric functions in JPQL still do not work as expected #1583 .

In the Criteria API test examples, I tried to apply `ceiling`, `floor`, `round with 1 scale` on a salary value `12345.678`.

It should return `12346, 12345, 12345.7`, but in the query result, all return `12,345`(`Double` type).

Check the [CriteriaBuilder test example](https://github.com/hantsy/jakartaee10-sandbox/blob/master/jpa/src/test/java/com/example/it/JPQLCriteriaBuilderTest.java#L116).

**Comment by Tomas-Kraus** [comment]
Added following code to EclipseLink master `org.eclipse.persistence.jpa.test.criteria.TestMathFunctions`:
```
    // Call CEILING(n) on Float 12345.678F.
    @Test
    public void testCeilingIssue1593() {
        try (final EntityManager em = emf.createEntityManager()) {
            CriteriaBuilder cb = em.getCriteriaBuilder();
            CriteriaQuery<Float> cq = cb.createQuery(Float.class);
            Root<NumberEntity> number = cq.from(NumberEntity.class);
            cq.select(cb.ceiling(number.get("floatValue")));
            cq.where(cb.equal(number.get("id"), 10));
            Float result = em.createQuery(cq).getSingleResult();
            Assert.assertEquals(Float.valueOf(12346F), result);
        }
    }


    // Call FLOOR(n) on Float 12345.678F.
    @Test
    public void testFloorIssue1593() {
        try (final EntityManager em = emf.createEntityManager()) {
            CriteriaBuilder cb = em.getCriteriaBuilder();
            CriteriaQuery<Float> cq = cb.createQuery(Float.class);
            Root<NumberEntity> number = cq.from(NumberEntity.class);
            cq.select(cb.floor(number.get("floatValue")));
            cq.where(cb.equal(number.get("id"), 10));
            Float result = em.createQuery(cq).getSingleResult();
            Assert.assertEquals(Float.valueOf(12345F), result);
        }
    }

    // Call ROUND(n,1) on Float 12345.678F.
    @Test
    public void testRoundIssue1593() {
        try (final EntityManager em = emf.createEntityManager()) {
            CriteriaBuilder cb = em.getCriteriaBuilder();
            CriteriaQuery<Float> cq = cb.createQuery(Float.class);
            Root<NumberEntity> number = cq.from(NumberEntity.class);
            cq.select(cb.round(number.get("floatValue"), 1));
            cq.where(cb.equal(number.get("id"), 10));
            Float result = em.createQuery(cq).getSingleResult();
            Assert.assertEquals(Float.valueOf(12345.7F), result);
        }
    }
```
All 3 tests passed. This is not a bug in EclipseLink.
Looks like EclipseLink library was not yet updated in Glassfish.

**Comment by hantsy** [comment]
Did you try to use `BigDecimal` for the number type, I also encountered this issue, #1641

**Comment by Tomas-Kraus** [comment]
Yes, Derby emulation is another story. That database is missing some of the functions defined in spec so they must be emulated somehow. And expression evaluation in Derby may change returned type. I'll have a look at it.
