### ISSUE TITLE
Plans / roadmap for 4.0.0 final release?

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/eclipselink#1640]
As one of the last Jakarta implementations projects, EclipseLink has not yet released a final version for the Jakarta EE 10 release.

Is there any target date or plan? I noticed there's no milestone for 4.0 here: https://github.com/eclipse-ee4j/eclipselink/milestones

**Comment by dmatej** [comment]
https://github.com/eclipse-ee4j/eclipselink/compare/4.0.0-M3...HEAD

**Comment by lukasj** [comment]
95% of changes in master from M3 are related to tests (~2k "new", few more k updated, some fixed etc)

**Comment by arjantijms** [comment]
Thanks @lukasj, sounds good!

**Comment by dmatej** [comment]
> 95% of changes in master from M3 are related to tests (~2k "new", few more k updated, some fixed etc)

Hi, any news? I see just recently released 3.0.3.

**Comment by lukasj** [comment]
If nightly build pass tonight, RC1 will be tomorrow

**Comment by lukasj** [comment]
4.0.0-RC1 is in central

**Comment by arjantijms** [comment]
> 4.0.0-RC1 is in central

Thanks, have just integrated it into GlassFish: https://github.com/eclipse-ee4j/glassfish/pull/24100

**Comment by arjantijms** [comment]
@lukasj any progress with getting 4.0 final released?

**Comment by arjantijms** [comment]
cc @dmatej

**Comment by arjantijms** [comment]
There has been a lot of progress reported here: https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/370

There seems to be a holdup here though: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24195

@ivargrimstad @waynebeaton is there anything we can do to unblock whatever is blocking there?

**Comment by ivargrimstad** [comment]
I've pinged the IP team to see what's going on

**Comment by arjantijms** [comment]
Everything seems to be resolved now: https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/370

@lukasj can you push 4.0 now?

**Comment by lukasj** [comment]
@arjantijms I do read emails and I do get notifications ;-) No, I cannot push 4.0 now as it has to be built first - give it few days

**Comment by arjantijms** [comment]
Thanks @lukasj let me know when you succeeded with building it (and staged it). I can do a final test in GF with the TCK and all if you like.

**Comment by lukasj** [comment]
the final build is in staging

**Comment by arjantijms** [comment]
> the final build is in staging

Thanks! I'm going to test it in GF 7.

**Comment by arjantijms** [comment]
Results on GF are good. All green: https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1992/

**Comment by lukasj** [comment]
thanks for checking, it's on the way to central...
