### ISSUE TITLE
Incorrect JAR file listed in the documentation

### ISSUE THREAD

**Issue by vogella** [eclipse-ee4j/eclipselink#1667]
https://www.eclipse.org/eclipselink/documentation/3.0/solutions/testingjpa004.htm#CHDEECDB explains how to activate weaving 

java -javaagent:eclipselink.jar

But I see no eclipselink.jar in the JARs from the 3.0 release. Do you mean org.eclipse.persistence.jpa?

If yes, please let me know there the docutation is so that I can provide a PR for a update or please fix the documentation directly.

![image](https://user-images.githubusercontent.com/139910/185931180-4d9baa4d-c7a4-4893-bf9a-c3f37a526078.png)

**Comment by lukasj** [comment]
see https://search.maven.org/artifact/org.eclipse.persistence/eclipselink/3.0.3/jar

**Comment by vogella** [comment]
Thanks @lukasj  for the link to the JAR file.
