### ISSUE TITLE
Error execution delete operation without identification_variable

### ISSUE THREAD

**Issue by bvfalcon** [eclipse-ee4j/eclipselink#1727]
By executing `DELETE FROM entity_name` Eclipselink 3.0.3 gives a NullPointerException error. But execution `DELETE FROM entity_name x` works correctly.

Identification variable is required, but specification [defines it as optional](https://jakarta.ee/specifications/persistence/3.0/jakarta-persistence-spec-3.0.html#a5636).

See [demonstration project](https://github.com/bvfalcon/eclipselink-delete-test) for details.

Environment:
* Eclipselink 3.0.3
* Derby database driver 10.15
* Java 11

**Comment by Tomas-Kraus** [comment]
Added simple jUnit into development branch:
```
    @Test
    public void testDeleteEntityWithoutAlias() {
        final String jpql = "DELETE FROM SimpleEntity";
        final EntityManager em = emf.createEntityManager();
        try {
            em.getTransaction().begin();
            Query q = em.createQuery(jpql);
            q.executeUpdate();
            em.getTransaction().commit();
        } finally {
            if (em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            em.close();
        }
    }
```
And this test passed:
```
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.012 s - in org.eclipse.persistence.jpa.test.jpql.TestBasicJPQL
```
So looks like future 4.0 is OK.
Will try 3.x branch now.

**Comment by dazey3** [comment]
Are we sure the JPA Specification intended to allow for:
```java
    Query query = em.createQuery("DELETE FROM Employee WHERE firstName = :fName AND lastName = :lName");
    query.setParameter("fName", "Peter");
    query.setParameter("lName", "Parker");
    query.executeUpdate();
```

The examples provided in the specification don't specifically include one where no identification variable is supplied and this query syntax looks more like a NativeQuery than a JPQL one... I know that isn't necessarily concrete evidence, but this query just looks incorrect to me.

I wonder if the JPA Specification is just wrong, or rather not verbose enough to describe the real intention; something like:

```
    delete_statement ::= simple_delete_clause | where_delete_clause where_clause
    simple_delete_clause := DELETE FROM entity_name [[AS] identification_variable]
    where_delete_clause := DELETE FROM entity_name [AS] identification_variable
```
