### ISSUE TITLE
Can't use UUID primary key with JPA 3.1 on PostgreSQL

### ISSUE THREAD

**Issue by mthmulders** [eclipse-ee4j/eclipselink#1771]
I am building an application with Jakarta EE 10 and JPA 3.1. The JPA-implementation is provided by OpenLiberty: EclipseLink 4.0.0.v202210051929.

My entity looks like this:

```java
@Entity
@NamedQueries({
    @NamedQuery(name = "Car.findById", query = "select c from Car c where c.id = :id")
})
@Table(name = "car")
public class Car {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;
    private String model;
    private Double price;
    // getters and setters omitted for brevity
}
```

The repository looks like this:

```java
public class CarRepository {
    private EntityManager em;

    public CarRepository(EntityManager em) {
        this.em = em;
    }

    public void store(Car car) {
        em.merge(car);
    }

    public Optional<Car> findById(UUID id) {
        return em.createNamedQuery("Car.findById", Car.class)
                .setParameter("id", id)
                .getResultStream()
                .findFirst();
    }
}
```

And finally, the PostgreSQL table is created using

```sql
create table car
(
    id uuid primary key,
    model varchar not null,
    price real not null
);
```

Now, I want to store a `Car` instance:

```java
var car = new Car();
car.setId(UUID.randomUUID());
car.setModel("Model");
car.setPrice(10_000d);

repository.store(car);
```

But it fails with

```
Internal Exception: org.postgresql.util.PSQLException: ERROR: operator does not exist: uuid = character varying
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 44
Error Code: 0
Call: SELECT ID, MODEL, PRICE FROM car WHERE (ID = ?)
	bind => [6c7f5f3d-2c71-4f2e-a79b-ca6a804670bc]
Query: ReadObjectQuery(referenceClass=Car )
```

The [attached project](https://github.com/eclipse-ee4j/eclipselink/files/10345227/eclipselink-jpa31-postgresql-uuid.zip) is a simplified version (without OpenLiberty) but illustrates the same problem.

If I understand [the specification](https://jakarta.ee/specifications/persistence/3.1/jakarta-persistence-spec-3.1.pdf) correctly, it should be possible to declare fields with type `UUID` without having to write a `AttributeConverter` anymore.

Did I make an obvious mistake (please point me at it!), did I mis-interpret the JPA spec, or is this a bug in EclipseLink?

**Comment by Netskeh** [comment]
to add a bit of information, I have a similar situation.

I just converted a JEE 8 application to Jakarta EE 10 and still have the old UUID AttributeConverters around.
The effect of removing the converters is already described above. 
Keeping the converters allows me to read & write entities with UUID attributes to Postgresql. However if a linked entity has to be lazy loaded then I get the same error message.

**Comment by rfelcman** [comment]
Fixed by https://github.com/eclipse-ee4j/eclipselink/pull/1778
