### ISSUE TITLE
EclipseLink 4.0 has been removed from the project homepage & documentation

### ISSUE THREAD

**Issue by lgf10** [eclipse-ee4j/eclipselink#1909]
All mentions of the release 4.0 have been removed:

![image](https://github.com/eclipse-ee4j/eclipselink/assets/55838482/437a76fc-fd96-4ab8-b0a4-03af6a9d3e2c)
https://eclipse.dev/eclipselink/#download
![image](https://github.com/eclipse-ee4j/eclipselink/assets/55838482/3c316eea-4d17-4212-a589-9a03cfe289e7)
https://eclipse.dev/eclipselink/releases/

The documentation for 4.0 also no longer exists: https://eclipse.dev/eclipselink/documentation/

**Comment by rfelcman** [comment]
It's fixed now by Eclipse.org stuff see comments at: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3401
