### ISSUE TITLE
OptimisticLockException does not give any details if batch is active

### ISSUE THREAD

**Issue by vavishal** [eclipse-ee4j/eclipselink#1938]
When batch-writing is active and an OptimisticLockException appears then the message says "One or more objects cannot be updated because it has changed or been deleted since it was last read".

The above error message doesn't give details like which statement in batch execution has failed

So in the fix added parameters list which has failed for the SQL query during batch execution
This will be fixed as part of PR https://github.com/eclipse-ee4j/eclipselink/pull/1936

**Comment by vladziv** [comment]
This solution applies only when parameter binding is turned on, the ParameterizedSQLBatchWritingMechanism class is used. When parameter binding is turned off, the DynamicSQLBatchWritingMechanism is used instead. Opened issue https://github.com/eclipse-ee4j/eclipselink/issues/2742
