### ISSUE TITLE
LocalTimeDate Failure

### ISSUE THREAD

**Issue by StudySteve** [eclipse-ee4j/eclipselink#1939]
Hello, 

I have a problem in glassfish with eclipselink.

I get this Exception, but I have the new versions - so I don't understand why the LocalTimeDate is not working:

<html>
<body>

Exception while preparing the app : Exception [EclipseLink-28018] (Eclipse Persistence Services - 4.0.1-RC2.v202302221144): org.eclipse.persistence.exceptions.EntityManagerSetupException Exception Description: Predeployment of PersistenceUnit [tsp-data] failed. Internal Exception: Exception [EclipseLink-7165] (Eclipse Persistence Services - 4.0.1-RC2.v202302221144): org.eclipse.persistence.exceptions.ValidationException Exception Description: The type [class java.time.LocalDateTime] for the attribute [erinnerung] on the entity class [class com.manage.model.Termin] is not a valid type for a temporal mapping. The attribute must be defined as java.util.Date or java.util.Calendar. Local Exception Stack:  Exception [EclipseLink-28018] (Eclipse Persistence Services - 4.0.1-RC2.v202302221144): org.eclipse.persistence.exceptions.EntityManagerSetupException Exception Description: Predeployment of PersistenceUnit [tsp-data] failed. Internal Exception: Exception [EclipseLink-7165] (Eclipse Persistence Services - 4.0.1-RC2.v202302221144): org.eclipse.persistence.exceptions.ValidationException Exception Description: The type [class java.time.LocalDateTime] for the attribute [erinnerung] on the entity class [class com.manage.model.Termin] is not a valid type for a temporal mapping. The attribute must be defined as java.util.Date or java.util.Calendar. 	at org.eclipse.persistence.exceptions.EntityManagerSetupException.predeployFailed(EntityManagerSetupException.java:233) 	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.createPredeployFailedPersistenceException(EntityManagerSetupImpl.java:2150) 	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.predeploy(EntityManagerSetupImpl.java:2126) 	at org.eclipse.persistence.jpa.PersistenceProvider.createContainerEntityManagerFactoryImpl(PersistenceProvider.java:347) 	at org.eclipse.persistence.jpa.PersistenceProvider.createContainerEntityManagerFactory(PersistenceProvider.java:313) 	at org.glassfish.persistence.jpa.PersistenceUnitLoader.loadPU(PersistenceUnitLoader.java:222) 	at org.glassfish.persistence.jpa.PersistenceUnitLoader.<init>(PersistenceUnitLoader.java:126) 	at org.glassfish.persistence.jpa.JPADeployer$1.visitPUD(JPADeployer.java:319) 	at org.glassfish.persistence.jpa.JPADeployer$PersistenceUnitDescriptorIterator.iteratePUDs(JPADeployer.java:546) 	at org.glassfish.persistence.jpa.JPADeployer.createEMFs(JPADeployer.java:326) 	at org.glassfish.persistence.jpa.JPADeployer.prepare(JPADeployer.java:168) 	at com.sun.enterprise.v3.server.ApplicationLifecycle.prepareModule(ApplicationLifecycle.java:986) 	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:469) 	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:259) 	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:467) 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:529) 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:525) 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) 	at java.base/javax.security.auth.Subject.doAs(Subject.java:376) 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:524) 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:555) 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:547) 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) 	at java.base/javax.security.auth.Subject.doAs(Subject.java:376) 	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:546) 	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1456) 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1825) 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1701) 	at com.sun.enterprise.v3.admin.AdminAdapter.doCommand(AdminAdapter.java:510) 	at com.sun.enterprise.v3.admin.AdminAdapter.onMissingResource(AdminAdapter.java:200) 	at org.glassfish.grizzly.http.server.StaticHttpHandlerBase.service(StaticHttpHandlerBase.java:150) 	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:453) 	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:145) 	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174) 	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153) 	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196) 	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88) 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246) 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178) 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118) 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96) 	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51) 	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510) 	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82) 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83) 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101) 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535) 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515) 	at java.base/java.lang.Thread.run(Thread.java:833) Caused by: Exception [EclipseLink-7165] (Eclipse Persistence Services - 4.0.1-RC2.v202302221144): org.eclipse.persistence.exceptions.ValidationException Exception Description: The type [class java.time.LocalDateTime] for the attribute [erinnerung] on the entity class [class com.manage.model.Termin] is not a valid type for a temporal mapping. The attribute must be defined as java.util.Date or java.util.Calendar. 	at org.eclipse.persistence.exceptions.ValidationException.invalidTypeForTemporalAttribute(ValidationException.java:1158) 	at org.eclipse.persistence.internal.jpa.metadata.converters.TemporalMetadata.process(TemporalMetadata.java:130) 	at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.MappingAccessor.processTemporal(MappingAccessor.java:2113) 	at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.MappingAccessor.processMappingConverter(MappingAccessor.java:1886) 	at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.MappingAccessor.processMappingValueConverter(MappingAccessor.java:1913) 	at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.BasicAccessor.process(BasicAccessor.java:438) 	at org.eclipse.persistence.internal.jpa.metadata.MetadataDescriptor.processMappingAccessors(MetadataDescriptor.java:1542) 	at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.ClassAccessor.processMappingAccessors(ClassAccessor.java:1659) 	at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.EntityAccessor.processMappingAccessors(EntityAccessor.java:1235) 	at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.EntityAccessor.process(EntityAccessor.java:694) 	at org.eclipse.persistence.internal.jpa.metadata.MetadataProject.processStage2(MetadataProject.java:1874) 	at org.eclipse.persistence.internal.jpa.metadata.MetadataProcessor.processORMMetadata(MetadataProcessor.java:600) 	at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.processORMetadata(PersistenceUnitProcessor.java:644) 	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.predeploy(EntityManagerSetupImpl.java:2047) 	... 46 more
--

</body>
</html>

**Comment by StudySteve** [comment]
package com.manage.model;

import jakarta.persistence.*;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

@Entity
@Table(schema="public", name="erinnerung")
@NamedQueries({
        @NamedQuery(
                name = "Erin.findbycustomer",
                query = "SELECT e FROM Erinnerung e WHERE e.customers.id = :customerid"
        ),
        @NamedQuery(
                name = "Erin.findbyuser",
                query = "SELECT e FROM Erinnerung e WHERE e.users.id = :userid"
        )
})
public class Erinnerung implements Serializable {
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;
    @ManyToOne
    @JoinColumn(name = "userid")
    private Users users;
    @ManyToOne
    @JoinColumn(name = "customerid")
    private Customers customers;
    @Basic
    @Column(name = "zeit")
    private LocalDateTime zeit;
    @Lob
    @Column(name = "erinnerung")
    private String erinnerung;
    @Basic
    @Column(name = "erledigt")
    private Boolean erledigt;

    public Erinnerung() {
    }

    public Erinnerung(String erinnerung) {
        this.erinnerung = erinnerung;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Users getUsers() {
        return users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    public Customers getCustomers() {
        return customers;
    }

    public void setCustomers(Customers customers) {
        this.customers = customers;
    }

    public LocalDateTime getZeit() {
        return zeit;
    }

    public void setZeit(LocalDateTime zeit) {
        this.zeit = zeit;
    }

    public String getErinnerung() {
        return erinnerung;
    }

    public void setErinnerung(String erinnerung) {
        this.erinnerung = erinnerung;
    }

    public Boolean getErledigt() {
        return erledigt;
    }

    public void setErledigt(Boolean erledigt) {
        this.erledigt = erledigt;
    }

    @Override
    public String toString() {
        return "{" +
                getZeit() +
                getErinnerung() +
                getErledigt() +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Erinnerung that = (Erinnerung) o;
        return Objects.equals(id, that.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
}

**Comment by AleksNo** [comment]
Hello, 

the error message states, that there is something wrong in the class "class com.manage.model.Termin". Please post this class so we can look into it.


Cheers
