### ISSUE TITLE
Presize HashMap allocations in UnitOfWorkImpl

### ISSUE THREAD

**Issue by Zuplyx** [eclipse-ee4j/eclipselink#1957]
I've noticed, that there are several places in `UnitOfWorkImpl` where HashMaps are created without specifying an initial size even though their expected size is known or can be reliably estimated. This can lead to unnecessary resizing and rehashing operations, which will hurt performance, especially for large UnitOfWork.

I will provide PRs to fix this for master and 2.7

**Comment by patric-r** [comment]
Note: In some of our "large unitofwork" use cases this change will improve throughput by ~1% 
which I find quite significant for such a rather simple improvement.
