### ISSUE TITLE
class was compiled with an unsupported JDK

### ISSUE THREAD

**Issue by TomasCerdeyra** [eclipse-ee4j/eclipselink#1968]
Estoy usando JDK 20. No es compatible con eclipse?

[EL Warning]: metadata: 2023-10-12 08:19:19.833--ServerSession(1725397913)--The com.mycompany.apppeluqueriacanina.logica.Duenio class was compiled with an unsupported JDK. Report this error to the EclipseLink open source project.
java.lang.IllegalArgumentException: Unsupported class file major version 63
[EL Severe]: metadata: 2023-10-12 08:19:19.837--ServerSession(1725397913)--The com.mycompany.apppeluqueriacanina.logica.Duenio class was compiled with an unsupported JDK. Report this error to the EclipseLink open source project.
java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 0
[EL Warning]: metadata: 2023-10-12 08:19:19.838--ServerSession(1725397913)--The com.mycompany.apppeluqueriacanina.logica.Mascota class was compiled with an unsupported JDK. Report this error to the EclipseLink open source project.
java.lang.IllegalArgumentException: Unsupported class file major version 63
[EL Severe]: metadata: 2023-10-12 08:19:19.838--ServerSession(1725397913)--The com.mycompany.apppeluqueriacanina.logica.Mascota class was compiled with an unsupported JDK. Report this error to the EclipseLink open source project.
java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 0
[EL Info]: 2023-10-12 08:19:19.873--ServerSession(1725397913)--EclipseLink, version: Eclipse Persistence Services - 2.7.10.v20211216-fe64cd39c3
[EL Warning]: metamodel: 2023-10-12 08:19:20.165--The collection of metamodel types is empty. Model classes may not have been found during entity search for Java SE and some Java EE container managed persistence units.  Please verify that your entity classes are referenced in persistence.xml using either <class> elements or a global <exclude-unlisted-classes>false</exclude-unlisted-classes> element
------------------------------------------------------------------------

**Comment by lukasj** [comment]
use newer build of 2.7; the latest one is 2.7.13
