### ISSUE TITLE
BatchFetch IN fails to fetch eager reference when selecting non-root entity

### ISSUE THREAD

**Issue by andilem** [eclipse-ee4j/eclipselink#2011]
EclipseLink version 4.0.2

When selecting a non-root entity (e.g. `query.select(root.get(child))`) and child has a `@ManyToOne` reference with `@BatchFetch(value=IN)`, the references of the children are not fetched. They are just `null`, even with `fetchType=EAGER`.

There is a simple test case attached with
- three entity types with unidirectional (eager) many-to-one references (Record -> User -> Company)
- User -> Company reference has `@BatchFetch(value=IN)`
- `query.select(query.from(Record.class).get("user"))`
- `em.createQuery(query).getResultList()` returns users with `company = null`
- when removing `@BatchFetch(value=IN)`, everything works as expected

[eclipselink-batchfetch-selectnonroot.zip](https://github.com/eclipse-ee4j/eclipselink/files/13499248/eclipselink-batchfetch-selectnonroot.zip)

**Comment by impacsl** [comment]
We have similar issues with OneToOne-references with three entities using BatchFetchType IN/JOIN/EXISTS:

Record - OneToMany / LAZY - Transaction - OneToOne / BatchFetch - Communication

In some cases the List of Transactions contains Communications that are null.

When removing the @BatchFetch it works as well as expected.

EclipseLink 4.0.2, but also other versions (4.0.1, 2.7.14)

**Comment by Sheikah45** [comment]
This issue can probably be closed now with #2303 being merged

**Comment by rfelcman** [comment]
Fix into 4.0 is #2310 . I'm closing it.
