### ISSUE TITLE
Lazy collections are fetched on detach

### ISSUE THREAD

**Issue by luisfpg** [eclipse-ee4j/eclipselink#2017]
I've recently migrated from javax to jakarta, from Eclipselink 2.x to 4.0.2.
Something that didn't happen before, but is happening with 4.0.2 is that when calling `em.detach(entity)`, if the entity has an uninitialized lazy collection, it gets fetched in the detach operation.
This is a high impact bug, as it could potentially load fetch a lot of db rows to memory.
In the project I work, we have many mapped `@OneToMany` collections which are private, and are only there to cascade deletes.
And we do a lot of detach to prevent many objects from end up in memory.
With this bug, the result is the exact opposite...

I have created a minimal project to reproduce the issue: https://github.com/luisfpg/eclipselink-detach-bug

I'm copying here parts of the README to make it easier to screen the problem:

This is the code to reproduce the issue:

```
var state = em.find(State.class, "s1");
var cities = (IndirectSet<City>) state.getCities();
System.out.printf("Is collection initialized? %s%n", cities.isInstantiated());
System.out.println("Before detach");
em.detach(state);
System.out.printf("State %s detached%n", state.getCode());
System.out.printf("Is collection initialized? %s%n", cities.isInstantiated());
```

And the output is:

```
[EL Info]: 2023-12-06 08:02:59.36--ServerSession(232307208)--EclipseLink, version: Eclipse Persistence Services - 4.0.2.v202306161219
Loaded state s1
Is collection initialized? false
Before detach
Loaded state s1
Loaded city s1b
Loaded city s1a
State s1 detached
Is collection initialized? true
```

Note that the collection gets initialized by the detach operation, which makes no sense.

**Comment by rfelcman** [comment]
Sorry but I don't see any issue there.
Why? Because of `FetchType.LAZY`. Example code at line no 2 `var cities = (IndirectSet<City>) state.getCities();` will fetch data, but cities are not accessed. Try to add behind line 2 something like `cities.size();`. What happens in next `System.out.printf("Is collection initialized? %s%n", cities.isInstantiated());`?
Or call it in the debugger. It will print `true`. `isInstantiated()` is more about first access from the user code to the `IndirectSet` or `IndirectList`.

**Comment by luisfpg** [comment]
Yes, I understand that if I call, for example, `size()` in a collection, it will be fetched.
The issue I'm reporting is that lazy collections are being initialized during a `em.detach` with the 'master' entity, without the collection having been previously initialized.
When enabling SQL logging in the example project, I have this log:

```
[EL Info]: 2024-01-08 09:30:07.127--ServerSession(232307208)--EclipseLink, version: Eclipse Persistence Services - 4.0.2.v202306161219
[EL Fine]: sql: 2024-01-08 09:30:07.301--ServerSession(232307208)--Connection(908084672)--SELECT COUNT(CODE) FROM STATE
[EL Fine]: sql: 2024-01-08 09:30:07.303--ServerSession(232307208)--Connection(908084672)--SELECT CODE, NAME FROM STATE WHERE (CODE = ?)
	bind => [s1]
Loaded state s1
Is collection initialized? false
Before detach
[EL Fine]: sql: 2024-01-08 09:30:07.313--ServerSession(232307208)--Connection(908084672)--SELECT CODE, NAME, STATE_CODE FROM CITY WHERE (STATE_CODE = ?)
	bind => [s1]
Loaded state s1
Loaded city s1a
Loaded city s1b
State s1 detached
Is collection initialized? true
```

Note that after the 'Before detach' log, we have the SQL executed: 'SELECT CODE, NAME, STATE_CODE FROM CITY WHERE (STATE_CODE = ?)'.
What if there would be thousands of cities?
Do the collections really need to be initialized by the `detach` operation?
This didn't happen with EclipseLink 2.x.

We detach entities as part of our framework, and there are collections with potentially tens of thousands of rows.
Such large data sets started being fetched by `detach` operations after we upgraded from EclipseLink 2.x to 4.x, and moved from `javax` to `jakarta` dependencies.

**Comment by AleksNo** [comment]
Hello,

if you change the code:
@OneToMany(mappedBy = "state", cascade = CascadeType.REMOVE, fetch = FetchType.LAZY)

to:
@OneToMany(mappedBy = "state", cascade = CascadeType.ALL, fetch = FetchType.LAZY)

Does it work then?

Cheers

**Comment by luisfpg** [comment]
@AleksNo No, it presents the exact same result with `cascade = CascadeType.ALL`: the collection is fetched during the detach operation.

**Comment by rfelcman** [comment]
It seems that described behavior started by:
#348 
and there are some other PRs and bugs about `detach()`
https://bugs.eclipse.org/bugs/show_bug.cgi?id=541873
https://bugs.eclipse.org/bugs/show_bug.cgi?id=541391
#292
#298 
Somebody prefers Entity object tree consistence for `detach()` in LAZY loading You prefer avoid unnecessary DB calls.
I think, that solution will be some new persistence unit property like `eclipselink.detach.lazy.loading.strategy`.

**Comment by luisfpg** [comment]
The point is that the collection cascade type is only REMOVE, and doesn't include DETACH.
As such, in my opinion, the collection should not be fetched.
If it would be ALL or DETACH, ok, it would be expected that all collection elements were detached as well...
