### ISSUE TITLE
4-6% Startup Time Regression in EclipseLink 4.0.1

### ISSUE THREAD

**Issue by tkburroughs** [eclipse-ee4j/eclipselink#2048]
**Describe the bug**
There is a 4-6% Startup time regression in the Daytrader 10 benchmark, seen in Open Liberty that is related to the EclipseLink 4.0.0 to 4.0.1 update for for persistence-3.1 feature changes https://github.com/OpenLiberty/open-liberty/pull/24597

**To Reproduce**

    Measure Startup time in Open Liberty 230420230418-0035 build
    Measure Startup time in Open Liberty 230520230423-1101 build
    Compare the Difference in Startup time between builds

**Expected behavior**
By swapping EclipseLink 4.0.1 implementation back to 4.0.0 and run Startup time measurements we see that the Startup time regression is fixed.

**Additional context**
Diagnostic information:

    OpenLiberty Version:
    WebSphere Application Server 23.0.0.4 (1.0.76.cl230520230423-1101) on Eclipse OpenJ9 VM, version 11.0.17+8 (en_US)
    Affected feature(s): persistence-3.1
    Java Version:
    java version "11.0.17" 2022-10-18
    IBM Semeru Runtime Certified Edition 11.0.17.0 (build 11.0.17+8)
    Eclipse OpenJ9 VM 11.0.17.0 (build openj9-0.35.0, JRE 11 Linux amd64-64-Bit Compressed References 20221031_457 (JIT enabled, AOT enabled)
    OpenJ9 - e04a7f6c1
    OMR - 85a21674f
    JCL - 2767d3a0b2 based on jdk-11.0.17+8)

**Comment by tkburroughs** [comment]
See #2047 for changes that have resolved the performance difference in Open Liberty testing.

**Comment by rfelcman** [comment]
> @rfelcman Should this issue remain open until the fix is also delivered to the master branch?

But it's done by #2065
