### ISSUE TITLE
Stuck thread problem: unique tiny message number (1)

### ISSUE THREAD

**Issue by david0** [eclipse-ee4j/eclipselink#2166]
**Describe the bug**

We face an unresponsive application after its running some days.

We upgraded from 2.7.12 to 4.0.3 some weeks ago.

Here is the log: [log.txt](https://github.com/user-attachments/files/15800613/log.txt)

- EclipseLink version: 4.0.3
- Java/JDK version: 21

We failed to reproduce it so far.

**Comment by rfelcman** [comment]
Attached log indicates, that there is concurrency issue around `com.company.mds.projectlifecycle.entity.Delivery` and entity tree around `@OneToMany` `@ManyToOne`.
Maybe this part

```
...
at com.company.mds.projectlifecycle.service.DeliveryService.getDeliveryList(DeliveryService.java:128)
at com.company.mds.projectlifecycle.controller.DeliverySessionController.getDeliveryListWith(DeliverySessionController.java:49)
...
```
tries call/modify same entity instance (and related in the tree) from multiple threads at the same time.

Quick possible workaround should be:
Disable JPA L2 Cache
Prefer LAZY loading with @OneToMany

Best solution:
Analyze threads and find piece of application code when multiple threads tries create modify entity tree with same IDs but from different starting points.
NOTE; Some threads should be created automatically by frameworks e.g. Weld and async events.

**Comment by david0** [comment]
Thanks for your response.

It is true that our the `Delivery` entity can be loaded & modified from many threads and even trough different repositories. I would also prefer an design where entities are not accessible from multiple repositories, but that'll be a bigger re-write. 
But: _loading_ an entity from different threads in parallel does not sound like bad practice to me, is that already problematic?

Is there any documentation on this limitations to understand it further and for future reference?

I guess we can disable 2nd level cache for now, at least locally the performance impact seems irrelevant and we are pretty close to the DB anyway.

**Comment by rfelcman** [comment]
About threads, it's part of the Jakarta Persistence Spec
https://jakarta.ee/zh/specifications/persistence/3.1/jakarta-persistence-spec-3.1.pdf
Chapter: 7.2. Obtaining an EntityManager

>>But: loading an entity from different threads in parallel does not sound like bad practice to me, is that already problematic?
Be precise I'm meaning same entity instance with same @Id.
Think about entity tree not only single entity as I mentioned "Prefer LAZY loading with @OneToMany".
E.g.
First thread will fetch some Entity1 with attribute `@OneToMany(fetch=FetchType.EAGER)` which will be large one -> fetching take some time -> higher chance for a dead lock . During fetching incomplete entity instance (attribute with @Id is used as a cache key) is locked in JPA L2 cache to prevent modifications from other threads. 
Second thread will start with some entity (e.g. Entity1_1) from the tree refereed, but not fetched yet, by first thread by `@OneToMany(fetch=FetchType.EAGER)` from Entity1 with @ManyToOne and waiting for complete Entity1.
At the end first thread waiting for Entity1_1 and second one for Entity1.
Other thing is that entity instance in managed state is "monitored" by owning EntityManager instance. Passing this "living" entity to other EntityManager instance created by other thread should lead into unexpected changes in the DB.

**Comment by david0** [comment]
Thanks for your help, for me its clear now why our app loads might get deadlocked.
