### ISSUE TITLE
UUIDs fail with EclipseLink and Postgres

### ISSUE THREAD

**Issue by anija-anil** [eclipse-ee4j/eclipselink#2190]
When creating a query with a UUID, the parameter is set as a VARCHAR instead of a UUID, and is rejected by Postgres.

Here is an example of the failing query:
```
UUID uuid = p1.id;
List<?> result = em.createQuery("SELECT p FROM PurchaseOrder p WHERE p.id=?1")
                   .setParameter(1, uuid).getResultList();
```

**Comment by mswatosh** [comment]
There is some discussion on how to convert to a UUID in postgres here:
https://stackoverflow.com/questions/12771737/conversion-string-to-uuid-in-postgres-and-java/34652560#34652560

There is a recreate here: https://github.com/mswatosh/persistence-recreates/blob/1a2658d4e90ce56807bf7ecbc65455d1b8600f17/src/main/java/com/example/application/PersistenceService.java#L119

**Comment by rfelcman** [comment]
Sorry, but I don see any bug there against PostgreSQL see attached testcase.
[UUIDPostgreSQL.tar.gz](https://github.com/user-attachments/files/17227096/UUIDPostgreSQL.tar.gz)
See and change _pom.xml_ for EclipseLink and PostgreSQL JDBC driver version.
Required DB table must be created by _init.sql_ .
Two tests are located in:
- `com.oracle.jpa.bugtest.TestBug#persistUUIDUUIDTest` ... insert data (one row)
- `com.oracle.jpa.bugtest.TestBug#queryWithParameterUUIDUUIDEntityTest` ... query/select data by JPQL with UUID parameter.

**Comment by rfelcman** [comment]
I see some logical errors related with `id` field in the modified example.
- generated fields are available after commit
```
em.getTransaction().commit();
id = entity.getId();
```
- to pass `id` across tests methods `static` is needed
```
private static UUID id;
```
Without this `id` with `null` value is passed to `query.setParameter(1, id);`
If `id` is not `null` test passing against public `4.0.4` or `5.0.0-B03` and my local build 5.0.0-SNAPSHOT
See next version of _TestBug.java_ .
[TestBug.tar.gz](https://github.com/user-attachments/files/17259215/TestBug.tar.gz)

**Comment by mswatosh** [comment]
I think I've narrowed down the issue. When I use this in my persistence.xml:
```
            <property name="jakarta.persistence.schema-generation.database.action"
            value="drop-and-create"/>
```
It's creating the table as:
```
postgres=# \d TEST_TAB_UUID_UUID
                Table "public.test_tab_uuid_uuid"
 Column |          Type          | Collation | Nullable | Default 
--------+------------------------+-----------+----------+---------
 id     | character varying(255) |           | not null | 
 name   | character varying(255) |           |          | 
```

Where your working example was creating the table directly as this:
```
postgres=# \d TEST_TAB_UUID_UUID
                Table "public.test_tab_uuid_uuid"
 Column |          Type          | Collation | Nullable | Default 
--------+------------------------+-----------+----------+---------
 id     | uuid                   |           | not null | 
 name   | character varying(200) |           |          | 
```

So it seems like the schema generation is not creating the table correctly?

**Comment by martin-petzold** [comment]
I ran into this issue and this is really serious. Because there are a lot of wrong solutions posted online. A work-around ist to set the `columnDefinition` property:

```
@Id @GeneratedValue(strategy = GenerationType.UUID)
@Column(name = "id", columnDefinition = "UUID default gen_random_uuid()", updatable = false, nullable = false)
private UUID id = null;
```
