### ISSUE TITLE
Support Record as Embeddable

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/eclipselink#2203]
I tried to use a record as `@EmbeddedId` id in an entity.

```java
public record RecordEmbeddedId(String id, String id2) {
}

@Entity
public class RecordEmbeddedIdEntity {

    @EmbeddedId
    RecordEmbeddedId id;
    String name;

    // setters and getters
}
```

When running the testing codes to verify the record support, I got the following errors.

```bash
Exception Description: Predeployment of PersistenceUnit [defaultPU] failed.
Internal Exception: Exception [EclipseLink-7246] (Eclipse Persistence Services - 5.0.0-B02.v202404111748): org.eclipse.persistence.exceptions.ValidationException
Exception Description: The Entity class [class com.example.RecordEmbeddedIdEntity] has an embedded attribute [id] of type [class com.example.RecordEmbeddedId] which is NOT an Embeddabl
e class. Probable reason: missing @Embeddable or missing <embeddable> in orm.xml if metadata-complete = true. Please see server.log for more details. [status: CLIENT_ERROR reason: Bad Request]
```

If I add `@Embeddable` to record like this.

```java
@Embeddable
public record RecordEmbeddedId(String id, String id2) {
}
```

Run the tests, it will throw the following exceptions.

```bash
Exception [EclipseLink-63] (Eclipse Persistence Services - 5.0.0-B02.v202404111748): org.eclipse.persistence.exceptions.DescriptorException
Exception Description: The instance creation method [com.example.RecordEmbeddedId.<Default Constructor>], with no parameters, does not exist, or is not accessible.
Internal Exception: java.lang.NoSuchMethodException: com.example.RecordEmbeddedId.<init>()
Descriptor: RelationalDescriptor(com.example.RecordEmbeddedId --> [DatabaseTable(RECORDEMBEDDEDIDENTITY)])
```

**To Reproduce**
Steps/resources to reproduce the behavior:

- EclipseLink version 5.0.0-B02/Glassfish 8.0.0-M6
- Java/JDK version 21
- Testing codes, https://github.com/hantsy/jakartaee11-sandbox/blob/master/jpa/src/test/java/com/example/it/RecordEmbeddedIdTest.java

**Comment by rfelcman** [comment]
Implementation is https://github.com/eclipse-ee4j/eclipselink/pull/2163
nightly build will be available tomorrow at
https://download.eclipse.org/rt/eclipselink/nightly/5.0.0/
or from Jakarta Maven staging repository
https://jakarta.oss.sonatype.org/content/groups/staging/org/eclipse/persistence/
e.g. latest snapshot `org.eclipse.persistence:eclipselink`
https://jakarta.oss.sonatype.org/content/groups/staging/org/eclipse/persistence/eclipselink/5.0.0-SNAPSHOT/

**Comment by hantsy** [comment]
@rfelcman Verified in Glassfish 8.0.0-M8/EclipseLink 5.0.0-B03, it works when adding `@Embeddable` on the record class. 

But I have tried the same feature on Hibernate 7.0.0 BetaX, the `@Embeddable` is optional.
