### ISSUE TITLE
What is the currently the best way to set as default org.eclipse.persistence.jaxb.JAXBContextFactory implementation?

### ISSUE THREAD

**Issue by jacekzwroclawia** [eclipse-ee4j/eclipselink#2216]
I have two JAXBContextFactory implementation

```
org.glassfish.jaxb.runtime.v2.JAXBContextFactory
org.eclipse.persistence.jaxb.XMLBindingContextFactory
```

normally as suggested in [documentation](https://eclipse.dev/eclipselink/documentation/4.0/moxy/moxy.html#RUNTIME001) `jaxb.properties` file with text presented below should be enough to set default factory to `org.eclipse.persistence.jaxb.JAXBContextFactory`
```
jakarta.xml.bind.context.factory=org.eclipse.persistence.jaxb.JAXBContextFactory
```

However in Eclipse Link 4 with [Jakarta XML Binding 4.0](https://jakarta.ee/specifications/xml-binding/4.0/) looks like support for jaxb.properties file has been dropped, in this commit https://github.com/lukasj/jaxb-api/commit/3944789d934550680e40267189453e642dc0e635 of @lukasj. I can confirm that my `jaxb.properties` file is now ignored and system choose `org.glassfish.jaxb.runtime.v2.JAXBContextFactory` while calling ` JAXBContext jxbContext = JAXBContext.newInstance(clazz);`

1. What is currently the best way to choose default JAXBFactory to `org.eclipse.persistence.jaxb.JAXBContextFactory` or maybe I should just use explicite factory `org.eclipse.persistence.jaxb.JAXBContextFactory#createContext` from Moxy?

2. What is the best way of choosing factory if i want to use different JAXBContext for different files?

**Comment by lukasj** [comment]
one can control the factory through the `jakarta.xml.bind.JAXBContextFactory` property/system property - see [the lookup algorithm definition](https://jakarta.ee/specifications/xml-binding/4.0/apidocs/jakarta.xml.bind/jakarta/xml/bind/jaxbcontext#discovery-of-jakarta-xml-binding-implementation-heading) for details
