### ISSUE TITLE
javax.persistence still part of jar

### ISSUE THREAD

**Issue by Mau04** [eclipse-ee4j/eclipselink#232]
### Environment ###
Platform: OpenJDK 10.0.2
Operating system: macOS High Sierra
eclipselink version: 2.7.3

### Issue ###

When starting my application, I get the following error:

```java.lang.SecurityException: class "javax.persistence.PersistenceUtil"'s signer information does not match signer information of other classes in the same package```

The class that is mentioned here is part of the eclipselink jar, which is not signed.

According to this PR [](https://github.com/eclipse-ee4j/eclipselink/pull/199), the javax.persistence package was removed from the eclipselink jar.
If I extract the jar, I can see the package being in there.

Can you please tell me what I'm doing wrong?

Thank you very much.

**Comment by lukasj** [comment]
the change was done in master, which is 3.0.0, only. There is currently no plan to backport this to 2.7 stream

**Comment by Mau04** [comment]
Thank you. It works now. Are there any plans when 3.0.0 will be released?

**Comment by MGwiozda** [comment]
> the change was done in master, which is 3.0.0, only. There is currently no plan to backport this to 2.7 stream

How to use version 2.7 then when the SecurityException always occours? This makes this Version unusable. Or is there a workaround that I dont understand?

2.7 is the newest version and we are not able to use it because of this error.
