### ISSUE TITLE
Eclipselink MetaDataProject uses the wrong field in processStage2 

### ISSUE THREAD

**Issue by jvissers** [eclipse-ee4j/eclipselink#260]
While doing some investigation into migrating from Eclipselink 2.6.5 to Eclipselink 2.7.3 we found that the JPA canonical metamodel functionality is broken. Effectively this means that all queries that want to leverage the JPA canonical model result in NPEs. Debugging the issues shows that there is a change made in the processStage2 method of the MetaDataProject. Initially that method started with:

```// 266912: process metamodel mappedSuperclasses separately from entity descriptors
        for (MappedSuperclassAccessor msAccessor : m_metamodelMappedSuperclasses.values()) {
            if (! msAccessor.isProcessed()) {
                msAccessor.processMetamodelDescriptor();
            }
        }
```

Where as of 2.7.3 this starts with:

```// process metamodel mappedSuperclasses separately from entity descriptors
        for (MappedSuperclassAccessor msAccessor : getMappedSuperclasses()) {
            if (! msAccessor.isProcessed()) {
                msAccessor.processMetamodelDescriptor();
            }
        }
```

So instead of using the **metamodelMappedSuperclasses** it tries to go to work on the **mappedSuperclasseAccessors**

**Comment by dazey3** [comment]
Ok, it looks like this was from https://bugs.eclipse.org/bugs/show_bug.cgi?id=466271, @lukasj?

It looks like it comes down to **m_mappedSuperclasseAccessors** vs **m_metamodelMappedSuperclasses**. Perhaps this was a mistake in 466271 and `MetadataProject.getMetamodelMappedSuperclasses()` was meant to be used? 

Note that there is a veiled threat on `MetadataProject.getMetamodelMappedSuperclasses()`:

https://github.com/eclipse-ee4j/eclipselink/blob/2d76403ab001de59d5b5836744d87423051476b7/jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/metadata/MetadataProject.java#L1224-L1236

Do you have a test for that we can run on 2.7 that would demonstrate an error?

**Comment by dazey3** [comment]
Perhaps this comment may show some light on which map is intended to be used?

https://github.com/eclipse-ee4j/eclipselink/blob/2d76403ab001de59d5b5836744d87423051476b7/jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/metadata/MetadataProject.java#L649-L650

It looks like stage2 may be supposed to use `m_metamodelMappedSuperclasses` after all. Meaning that we need to change this back to `getMetamodelMappedSuperclasses()` as per the original implementation. That's my 2 cents tho. I would trust what @lukasj has to say on the subject tho.

**Comment by jvissers** [comment]
I verified that making this change, makes my integration test work again from the perspective of JPA canonical metamodel.

**Comment by jvissers** [comment]
Created a pull request; is now running in Travis. Conversation shows that ip-validation failed, no clue what to do about that. https://github.com/eclipse-ee4j/eclipselink/pull/261

**Comment by lukasj** [comment]
This should be checked against project set up outlined within https://bugs.eclipse.org/bugs/show_bug.cgi?id=540100

We're quite busy with transferring all Java EE projects to eclipse, so we'll get to this when there is a chance/window for other tasks
