### ISSUE TITLE
MOXy JSON: marshalling decimals as strings

### ISSUE THREAD

**Issue by nigredo-tori** [eclipse-ee4j/eclipselink#263]
We have an old project that uses MOXy to convert between XML and JSON representations of some data. The classes themselves are generated from an XSD schema using XJC. A few days ago we stumbled upon a problem, the root of which was that the large `xsd:decimal`/`BigDecimal` values were marshalled as JSON numbers. The spec allows it, however not all JSON libraries support this. In this particular case, JavaScript's `JSON.parse` attempted to convert the value to a JS number, losing precision in the process.

The easiest solution in my case would be to marshal `BigDecimal`s as JSON strings. However a custom `XmlAdapter<String, BigDecimal>` did not work off the bat - the values were still marshalled as JSON numbers. Further investigation shows that using `@XmlSchemaType("decimal")` for the field in question makes MOXy inject the marshalled string as a raw JSON value - that is, not quoted or checked - which can lead to invalid JSON!

It seems that there are two ways to marshal decimals as strings:
1. Remove the type metadata from the field (but only for JSON marshalling!). This requires maintaining conflicting metadata (probably using [this](https://www.eclipse.org/eclipselink/documentation/2.6/solutions/jpatoxml004.htm) - I haven't dug deep into it yet) for XML end JSON marshalling.
2. Abuse the weird `XmlAdapter` behavior so that it returns a quoted string. This `XmlAdapter` should only be used for marshalling to JSON. This also requires a conflicting metadata.

Both ways feel like hacks to me. Is there a better way to control the type of the resulting JSON value? At least something that can coexist with XML marshalling without me maintaining metadata overrides?

Here's an [SSCCE](https://github.com/nigredo-tori/various-examples/tree/master/java/eclipselink-adapter-type-bug).

**Comment by rfelcman** [comment]
Hello,
 I checked Your example and I found following. You want store large numbers into JSON as a string, but via `@XmlSchemaType("decimal")` You pushed MOXy to take `String` result from the adapter `CustomBigDecimalAdapter` and store it as a JSON number (without quotes). Word "decimal" is name of XML schema type [https://www.w3.org/TR/xmlschema-2/#decimal](https://www.w3.org/TR/xmlschema-2/#decimal) . I think, that right annotation there is `@XmlSchemaType("string")` .

**Comment by nigredo-tori** [comment]
@rfelcman, thank you. I've more or less figured that out. The problem is that the classes are automatically generated from an XSD (using `xjc`), and I'd like to keep it this way... I've ended up with a separate `eclipselink-oxm.xml` for the JSON encoding, with each of the fields in question mapped to the `string` XML type. This is ugly, but it gets the job done. There probably is some "middle ground" xjc configuration that satisfies both encodings, but I don't see it being any nicer.
