### ISSUE TITLE
org.eclipse.persistence.jpa depends on javax.json-api but doesn't use it

### ISSUE THREAD

**Issue by nictas** [eclipse-ee4j/eclipselink#273]
Hi,

I am migrating a Maven project from OpenJPA to EclipseLink JPA and I saw something which looked weird to me, so I thought I should report it. I added the following dependencies to my project's pom.xml:
```
            <dependency>
                <groupId>org.eclipse.persistence</groupId>
                <artifactId>org.eclipse.persistence.jpa</artifactId>
                <version>2.7.3</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.persistence</groupId>
                <artifactId>org.eclipse.persistence.extension</artifactId>
                <version>2.7.3</version>
            </dependency>
```
Unfortunately, due to my company's policy, I had to document all new dependencies (including transitive ones), so I went through them one by one. I saw that the `org.eclipse.persistence.jpa` artifact has a compile dependency to `javax.json-api` and I did a quick search through the code, but I couldn't find any usage of the `javax.json` package. I also tried excluding it and nothing broke. Is this dependency really necessary then? Removing it might save some time for other people in my situation.

**Comment by dazey3** [comment]
Hello! Hmmm, interesting, I don't see `javax.json` listed as a package import for the `org.eclipse.persistence.jpa` bundle. Where are you seeing a list of `compile` dependencies for these bundles?

**Comment by nictas** [comment]
Hi dazey,

Thanks for taking a look! I'm seeing this from Eclipse's "Dependency hierarchy" view over my pom.xml. Here's a screenshot:
https://ibb.co/gQEXq0

**Comment by nictas** [comment]
Thanks for the quick fix! :)

**Comment by lukasj** [comment]
2.7.4 will contain the fix as well
