### ISSUE TITLE
POSTGRESQL BIT(1) MAP TO BOOLEAN 

### ISSUE THREAD

**Issue by naxrd** [eclipse-ee4j/eclipselink#316]
When you map a table containing a bit(1) field in postgresql, eclipselink map it to a boolean field, when you retrieve the information from the database the information is obtained withoud problems but when you try to update or insert postgresql doen't accept true or false value for this field instead accept B'1' or B'0', if you try to use converter then the same stuff happed due to the type of parameter set for eclipselink to the query is boolean so it doenst accept data like string or other type.

**Comment by rfelcman** [comment]
Hello,
I checked this bug, but I don't think, that is an EclipseLink bug. There is trouble with some inconsistency in PostgreSQL JDBC driver. Driver can returns/converts BIT(1) into Java boolean, but during DML (PrepareStatement implementation) it doesn't accept it. It returns error message like this:
"ERROR: column "value" is of type bit but expression is of type boolean".
You can inspect `org.postgresql.jdbc.PgResultSet` and `org.postgresql.jdbc.PgPreparedStatement`.
In case of DML `org.postgresql.util.PGobject` could be used. So possible solution is use converter like this:
````
import org.postgresql.util.PGobject;
import javax.persistence.AttributeConverter;
import javax.persistence.Converter;
import java.sql.SQLException;

@Converter
public class TestConverter implements AttributeConverter<Boolean, PGobject> {


    @Override
    public PGobject convertToDatabaseColumn(Boolean value) {
        try {
            PGobject po = new PGobject();
            po.setType("BIT");
            if (value != null && value) {
                po.setValue("1");
            } else {
                po.setValue("0");
            }
            return po;
        } catch (SQLException e) {
            e.printStackTrace();
            return null;
        }
    }

    @Override
    public Boolean convertToEntityAttribute(PGobject value) {
        if (value != null && value.equals("t")) {
            return Boolean.TRUE;
        } else {
            return Boolean.FALSE;
        }
    }
}
````
Some weakness is, that there is direct usage of PostgreSQL JDBC driver class `org.postgresql.util.PGobject`.

**Comment by naxrd** [comment]
Thank you for your willingness to help, tried to solve it by myself but I am not too deep into the project yet.
