### ISSUE TITLE
Bug 547173 - EntityManager.unwrap(Connection.class) returns null

### ISSUE THREAD

**Issue by jgrassel** [eclipse-ee4j/eclipselink#437]
Eclipse bugtracker https://bugs.eclipse.org/bugs/show_bug.cgi?id=547173

An EntityManager, using an EntityManagerFactory with the property "eclipselink.jdbc.exclusive-connection.mode" set to "Always" returns a null value if the EntityManager hasn't been exercised in any operations that interact with the database (a simple em.find() will work around this issue.)  With a EntityManager that is configured to retain an exclusive connection it seems plausible that this should return a Connection.

**Comment by arunvc** [comment]
Connection is still null in 2.7.7

Connection is returned after 
EntityManager.getTransaction().begin() or a dummy EntityManager.find()
