### ISSUE TITLE
CommitManager.sort not working if primary key is a byte array 

### ISSUE THREAD

**Issue by nicolae-leonte-go** [eclipse-ee4j/eclipselink#466]
The issue is very well described here:

https://www.eclipse.org/forums/index.php/t/1095573/

In the org.eclipse.persistence.internal.identitymaps.CacheId.equals method the comparison is properly handled (identifying the underlying array and invoking the appropriate helper method).

I suspect something similar may be required in the CacheId.compareTo method. 

Swallowing/hiding the cast exception and returning 0 is very misleading...

**Comment by jpt-avaleo** [comment]
+1

**Comment by lukasj** [comment]
I believe this is a dup of #482 Feel free to reopen with more details if not. Thanks!
