### ISSUE TITLE
SDO Types generation is very slow for big schemas

### ISSUE THREAD

**Issue by asanitckii** [eclipse-ee4j/eclipselink#467]
[Link to BZ #548125](https://bugs.eclipse.org/bugs/show_bug.cgi?id=548125)

Happens in case of generation lots of SDO types, like a hundred thousand.

The generation is slow and the major bottleneck is the SDOType.setupInheritance method.
The profiling showed that the 2 methods consuming most of the time are:
1. NamespacesResolver#getNamespaces()
2. NamespacesResolver#put(String, String)

Call tree trace file is attached. - [Trace.zip](https://github.com/eclipse-ee4j/eclipselink/files/3282474/Trace.zip)

**Comment by rfelcman** [comment]
Duplicated with #676
