### ISSUE TITLE
CacheId#compareTo violates equals() contract, resulting in wrong number of entites deleted when @Id is of type byte[] 

### ISSUE THREAD

**Issue by jpt-avaleo** [eclipse-ee4j/eclipselink#482]
We have two entities, both that have UUID marked as `@Id` and with `BINARY(16)` as a MySQL representation of that. 

```
@Entity
@Table(name = "blog_entry")
@Convert(attributeName = "id", converter = UuidBinaryConverter.class)
public class BlogEntry {

	@Id
	@Column(name = "id", columnDefinition = "binary(16)")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "uuid_generator")
	private UUID id;

	@OneToMany(cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.EAGER)
	@JoinColumn(name = "blog_entry_id", referencedColumnName = "id", nullable = false)
	private Collection<Comment> comments = new ArrayList<>();

}
```
and
```
@Entity
@Table(name = "comment")
@Convert(attributeName = "id", converter = UuidBinaryConverter.class)
public class Comment {

	@Id
	@Column(name = "id", columnDefinition = "binary(16)")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "uuid_generator")
	private UUID id;


}
```
Please note `orphanRemoval = true` on comments, but this issue is not related only to unidirectional relationship, it happens with bi-directional as well. It's not limited to orphanRemoval either, if we did Spring Data JPA repository for Comment entity with a method `deleteByBlogEntryId(UUID blogEntryId)`  
for bi-directional relationship it will yield same results.

The issue here is that when I clear comments collection that originally had 10 values with `comments.clear()` and commit the transaction then only one of the elements to be deleted is actually being deleted from the database. 

This is due to the fact that `org.eclipse.persistence.internal.sessions.CommitManager#sort` and especially `org.eclipse.persistence.internal.identitymaps.CacheId#compareTo` implementations being broken. 

`org.eclipse.persistence.internal.identitymaps.CacheId#compareTo` for `byte[]` type catches `java.lang.ClassCastException` when casting `byte[]` to `java.lang.Comparable` and returns `0` value for all the elements, regardless of its actual value. That in turn means that `org.eclipse.persistence.internal.sessions.CommitManager#sort` returns only one value,  even if you pass a list with multiple objects. 

This results in only one of the elements being actually deleted, regardles of how many we pass. 

All of that is caused by `org.eclipse.persistence.internal.identitymaps.CacheId#compareTo` violating `equals()` contract described here: https://docs.oracle.com/javase/8/docs/api/java/lang/Comparable.html where it says 

> The natural ordering for a class C is said to be consistent with equals if and only if e1.compareTo(e2) == 0 has the same boolean value as e1.equals(e2) for every e1 and e2 of class C

Right now org.eclipse.persistence.internal.identitymaps.CacheId#equals correctly handles `byte[]` values, but `org.eclipse.persistence.internal.identitymaps.CacheId#compareTo` does not.

Possible fix for that would be to make `org.eclipse.persistence.internal.identitymaps.CacheId#compareTo` consistent with `equals()`.

**Comment by lukasj** [comment]
fixed in master and for 2.7.5
