### ISSUE TITLE
JPA Weave: File handle leak: persistence.xml not properly closed

### ISSUE THREAD

**Issue by jnehlmeier** [eclipse-ee4j/eclipselink#494]
On Windows, when calling `StaticWeave.main()` and then trying to delete `persistence.xml`, an exception will be thrown because `persistence.xml` is still opened by the java process. 

So I guess there is a leaking file handle / InputStream somewhere in the weaving code.

I encountered it in a Gradle build. Gradle puts classes and resources into different directories which is not expected by the JPA spec. In order to execute static weaving in Gradle, the build script copies the persistence.xml into the classes directory manually, then weave, and then delete the persistence.xml in the classes directory before building the final jar.

Basically:
```groovy
compileJava {
  ext.persistenceXml = "${sourceSets.main.resources.srcDirs.iterator().next()}/META-INF/persistence.xml"
  // after compilation, weave classes
  doLast {
    def destDirPath = destinationDir.toPath();
    def destMetaInfPath = destDirPath.resolve("META-INF")
    def destPersistenceXml = destDirPath.resolve("META-INF/persistence.xml")
    Files.createDirectories(destMetaInfPath)
    Files.copy(Paths.get(ext.persistenceXml), destPersistenceXml)
    String [] args = ....
    StaticWeave.main(args); // weave classes
    Files.delete(destPersistenceXml) // fails on Windows because file still opened
    Files.delete(destMetaInfPath)
  }
}
```

As a workaround the build needs to execute weaving in a new JVM using Gradle JavaExec task.

**Comment by rfelcman** [comment]
Fixed in master and 2.7 branches.
