### ISSUE TITLE
Bug 518774: SAP HANA DB 2.x is detected as DB2Platform instead of HANAPlatform

### ISSUE THREAD

**Issue by dazey3** [eclipse-ee4j/eclipselink#518]
Linking to [BZ #518774](https://bugs.eclipse.org/bugs/show_bug.cgi?id=518774)

**Comment by marcopar** [comment]
Hi, may i ask what exactly is branch 2.6_WAS and why this is not merged to 2.6?
Looks like 2.6.x releases don't have this fix while 2.7.x have it.
