### ISSUE TITLE
New Object created and deleted in nested UnitOfWork is commited to DB

### ISSUE THREAD

**Issue by Thorsten356** [eclipse-ee4j/eclipselink#624]
For a detailed description and example code see attachment. Tested with eclipselink 2.7.5.
[testEclipselink10nestedUOW.pdf](https://github.com/eclipse-ee4j/eclipselink/files/3927850/testEclipselink10nestedUOW.pdf)
[testEclipselink10nestedUOW.zip](https://github.com/eclipse-ee4j/eclipselink/files/3927851/testEclipselink10nestedUOW.zip)

**Comment by Thorsten356** [comment]
Successfully tested with my Testcase.

**Comment by rfelcman** [comment]
Fix for this bug was merged to master branch (3.0) and 2.7.7 branch/version. I am closing this bug now. If You will discover another trouble related with this bug, feel free to reopen it.
Nightly build with this fix is available at https://www.eclipse.org/eclipselink/downloads/nightly.php .

**Comment by Thorsten356** [comment]
Great, thanks a lot. Is there a release date for version 2.7.7?
Which link is prefered for new versions? I knew
https://projects.eclipse.org/projects/ee4j.eclipselink
https://www.eclipse.org/eclipselink/releases/

**Comment by rfelcman** [comment]
I think
https://www.eclipse.org/eclipselink/downloads/
or
Maven central
