### ISSUE TITLE
Incorrect javadoc for PersistenceUnitProperties.QUERY_TIMEOUT

### ISSUE THREAD

**Issue by mikekanani** [eclipse-ee4j/eclipselink#702]
I just upgraded a project to 2.7.5 and I can see that the default unit for `javax.persistence.query.timeout` has changed from seconds to milliseconds however the java doc still claims the default is seconds.

https://github.com/eclipse-ee4j/eclipselink/blob/master/foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/PersistenceUnitProperties.java#L3185

**Comment by rfelcman** [comment]
Sorry, but this is little bit strange. I don't know about any change in `javax.persistence.query.timeout` in last year (before 2.7.5 release). At the end it's handled by JDBC driver. I'd like simulate it. Could You please provide some info about JDBC driver (producer, version) and DB (producer, version).

**Comment by lukasj** [comment]
@dazey3 added support for setting `QUERY_TIMEOUT_UNIT` explicitly, see https://github.com/eclipse-ee4j/eclipselink/blob/master/foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/PersistenceUnitProperties.java#L3209

**Comment by mikekanani** [comment]
There isn't an issue with the code, just the javadoc. 

The javadoc for QUERY_TIMEOUT_UNIT has been updated to state that the default is milliseconds but QUERY_TIMEOUT still says "Defaults to seconds, but is configurable with PersistenceUnitProperties.QUERY_TIMEOUT_UNIT"

https://www.eclipse.org/eclipselink/api/2.7/org/eclipse/persistence/config/PersistenceUnitProperties.html#QUERY_TIMEOUT

**Comment by rfelcman** [comment]
Fix for this bug was merged to master branch (3.0) and 2.7.7 branch/version. I am closing this bug now. If You will discover another trouble related with this bug, feel free to reopen it.
Nightly build with this fix is available at https://www.eclipse.org/eclipselink/downloads/nightly.php .
