### ISSUE TITLE
Migrate project to maven

### ISSUE THREAD

**Issue by rieonke** [eclipse-ee4j/eclipselink#77]
Hi everyone!

Is there any plan to migrate to maven structured project?
Many Jakarta EE projects are maven based or have been migrated such as jsonp, mojarra and so on,
It's more convenient and clear to organize the whole complex project and easier to set up project in a new environment.

I would like to help if we can add it to our roadmap.
Thanks!

**Comment by jgrassel** [comment]
I think Gradle might be equally as good a contender for any sort of project migration.

**Comment by lukasj** [comment]
well, I could possibly share my private gradle branch if someone wants to follow up where I ended. It looked not that hard to migrate it but in the end there are some non-trivial things to resolve, such as running tests (I don't recall how far I got here), creating eclipse features and update sites and building oracle specific modules against oracle proprietary libraries where one of the libraries is not available in maven.oracle.com repo. In any case - any change to the build system which would mean dropping Tycho will lead to leaving manifest-first approach the build is currently relying on.

In my opinion, based on my own experience, it would be better to make sure that the project structure follows maven rules while it remains using Tycho and move non-Tycho 'enabled' subprojects (like eclipse features/plugins/updatesites builds) to tycho.

**Comment by arjantijms** [comment]
@jgrassel 
>I think Gradle might be equally as good a contender for any sort of project migration.

Probably, and perhaps even modern SBT would be a candidate. Still, since all other projects in EE4J are Maven based, for better or worse, I'd say Maven would really be the best choice here.

**Comment by sergeykad** [comment]
IMHO, the main issue in switching to Gradle is that there is no Tycho version for it. Other than that, it is easier to convert existing projects to Gradle than Maven due to much better configuration flexibility.

**Comment by lukasj** [comment]
this is currently being worked on in #381

**Comment by lukasj** [comment]
fixed by #381 ; build instructions are at: https://github.com/eclipse-ee4j/eclipselink/wiki/Building-EclipseLink#mvnbuild
