### ISSUE TITLE
What is eclipselink's primary bug tracker?

### ISSUE THREAD

**Issue by patric-r** [eclipse-ee4j/eclipselink#779]
Question here:
What is EclipseLink's primary (or better: only) bug tracker?

Github issues or eclipse bugzilla?

Having two different bugtrackers is confusing
(and btw, eclipse bugzilla is missing target milestone 2.7.6 and 2.7.7).

**Comment by cen1** [comment]
When I raised this issue on JakartaEE community mailing list someone told me that technically both are used. I personally tend to use github now that all Jakarta related projects are hosted here. Plus, the eclipse bugtracker seems like a wasteland.

**Comment by lukasj** [comment]
use whatever you prefer - both are being monitored but github is preferred.

btw: there also exists [a mailing list](https://accounts.eclipse.org/mailing-list/eclipselink-users) for this type of questions.

**Comment by patric-r** [comment]
@lukasj 
Thanks for your answer.

1. Are you encouraging your users to "migrate" (copy) important bug reports from bugzilla to github?

2. Previously, I used bugzilla as a replacement for a missing changelog (I filtered for resolved/fixed bugs for the desired target milestone(s)).
Because we have now more than one bugtracker:
How to get a complete changelog (e.g. for the new 2.7.7 release)?

Thanks!
