### ISSUE TITLE
Maven Central lists 3.0.0-M1 as Latest and Release version

### ISSUE THREAD

**Issue by Maldivia** [eclipse-ee4j/eclipselink#789]
It seems the the release of 3.0.0-M1 has completely overwritten the maven metadata file on Maven Central.

All proper release versions are no longer present in the file, and only the 3.0.0-M1 and 2.7.7-RC1 are listed in the file as valid versions.
Furthermore, 3.0.0-M1 is listed as the latest and the release version.
https://repo1.maven.org/maven2/org/eclipse/persistence/eclipselink/maven-metadata.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata>
  <groupId>org.eclipse.persistence</groupId>
  <artifactId>eclipselink</artifactId>
  <versioning>
    <latest>3.0.0-M1</latest>
    <release>3.0.0-M1</release>
    <versions>
      <version>2.7.7-RC1</version>
      <version>3.0.0-M1</version>
    </versions>
    <lastUpdated>20200504085535</lastUpdated>
  </versioning>
</metadata>
```

**Comment by lukasj** [comment]
reported to [sonatype](https://issues.sonatype.org/browse/MVNCENTRAL-5753), only they can fix this kind of issues

**Comment by lukasj** [comment]
give it an hour or two for the fix to get to mvn central. Thanks for the report!
