### ISSUE TITLE
Upgraded to Eclipselink 3.0.0 M1 = No Persistence provider for EntityManager named 

### ISSUE THREAD

**Issue by bsutton** [eclipse-ee4j/eclipselink#834]
I've just upgraded an existing eclipselink project to 3.0.0-m1.

When I start the tomcat 9.0 service I'm getting an error:

No Persistence provider for EntityManager named Auditor.

My pom is as follows:

```
	<!-- https://mvnrepository.com/artifact/org.eclipse.persistence/eclipselink -->
		<dependency>
			<groupId>org.eclipse.persistence</groupId>
			<artifactId>eclipselink</artifactId>
			<version>3.0.0-M1</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.persistence</groupId>
			<artifactId>javax.persistence</artifactId>
			<version>2.2.0</version>
		</dependency>
```

My persistence.xml contains:

```
<persistence xmlns="http://xmlns.jcp.org/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence
                                 http://xmlns.jcp.org/xml/ns/persistence/persistence_2_2.xsd"
  version="2.2">

	<persistence-unit name="Auditor"
		transaction-type="RESOURCE_LOCAL">
		<!-- This is where you mention your JPA runtime provider e.g. it's EclipseLink 
			here -->
		<provider>org.eclipse.persistence.jpa.PersistenceProvider</provider>
		<mapping-file>META-INF/orm.xml</mapping-file>
...
```

**Comment by lukasj** [comment]
this is expected since you need `jakarta.persistence:jakarta.persistence-api:3.0.0-RC2` instead of `org.eclipse.persistence:javax.persistence:2.2.0`

**Comment by bsutton** [comment]
So for others finding this issue, where is the doco on this requirement?

It's there a migration guide from 2.x?

**Comment by lukasj** [comment]
> So for others finding this issue, where is the doco on this requirement?

https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan

more to come once the release gets closer, M1 is there to sync up with other projects under the Jakarta EE 9 umbrella

> It's there a migration guide from 2.x?

that will be provided by EE 9 platform I believe. Short answer is replace all `javax.persistence` usages by `jakarta.persistence` and apply the same for almost all technologies which used to part of Java EE/Jakarta EE 8
