### ISSUE TITLE
Website suggests wrong source repositories

### ISSUE THREAD

**Issue by laeubi** [eclipse-ee4j/eclipselink#850]
As a follow up to #268 as @lukasj suggested I'm opening a new ticket.

I have tried to check out latest source and was a bit confused because the projects website still references old repositories. As I can't believe the project was "dead" googled around a little and foudn the project on github here.

### These are the references that leads me to the wrong track:

> https://www.eclipse.org/eclipselink > More > Check out the source code 

Links to https://git.eclipse.org/c/eclipselink/

> https://www.eclipse.org/eclipselink > More > Lear How To contribute

Links to https://wiki.eclipse.org/EclipseLink/Development/Process that references https://wiki.eclipse.org/EclipseLink/Development/Process/Git where http://git.eclipse.org/gitroot/eclipselink/eclipselink.runtime.git is mentioned.

**Comment by lukasj** [comment]
fixed by https://git.eclipse.org/c/www.eclipse.org/eclipselink.git/commit/?id=4764e556fd3f212020625b258d3edbbcdac37db3
