### ISSUE TITLE
Update Jakarta EE 9 persistence schemas 

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/eclipselink#886]
Please update orm/orm_3_0.xsd + persistence_3_0.xsd schemas to refer to https://jakarta.ee/xml/ns/persistence/orm/orm_3_0.xsd

**Comment by lukasj** [comment]
check following:

* orm_3_0.xsd (jpa)
* persistence_3_0.xsd (jpa)
* bindingschema_3_0.xsd (moxy)
* validation-mapping-3.0.xsd (moxy)
* jakartaee/web-app (dbws builder)

**Comment by jgrassel** [comment]
Is this issue ready to be closed?

**Comment by scottmarlow** [comment]
I believe it is ready to be closed.
