### ISSUE TITLE
Eclipselink and Java 9+ modularity

### ISSUE THREAD

**Issue by dsuiu-msys** [eclipse-ee4j/eclipselink#932]
I try to migrate a project from Java 8 to Java 11.
In the migration process I want to switch to the JPMS (Jigsaw) introduced in Java 9.
I use eclipselink 2.6.3 version (I tried 2.7.7 version but I got the same result).
For development I use Eclipse IDE (version 2020-09 (4.17.0)).
I will share some screenshots that show very well the nature of problem:
![image](https://user-images.githubusercontent.com/73169343/96574928-c4dd3780-12d8-11eb-8328-8c60b6751eee.png)
![image](https://user-images.githubusercontent.com/73169343/96575101-feae3e00-12d8-11eb-8560-8cfd23bc0ecb.png)

We use Gradle for build and we have this dependencies in project:
```
'org.eclipse.persistence:javax.persistence:2.2.1',
'org.eclipse.persistence:eclipselink:2.7.3',
```

I know that `eclipselink-2.7.7` has `org.eclipse.persistence:'jakarta.persistence:2.2.3` as dependency, but this does not change the data of the problem (the package `javax.persistence` is available in `eclipselink` and `javax/jakarta.persistence` and this duplication is not allowed by JPMS).

I have some question for you:
1. is it eclipselink (real) ready for applications that use JPMS?
2. did anyone use eclipselink with success in a JPMS application?
3. why eclipselink put some classes/interfaces in `javax.persistence` namespace and not in `org.eclipse.persistence` namespace? is it a good reason related to the presence of  `javax.persistence` in eclipselink jar (I didn't checked for sources)

Thank you in advance for your answer!

**Comment by sgflt** [comment]
JPMS is not yet mature to be used in production. I have tried migrate our app to JPMS too, but it revealed that only minority of frameworks is prepared. See https://developer.jboss.org/blogs/scott.stark/2017/04/14/critical-deficiencies-in-jigsawjsr-376-java-platform-module-system-ec-member-concerns for more information.

**Comment by dsuiu-msys** [comment]
@sgflt I understand perfectly what you say. The article is old (2017) and in the meantime things have improved.
I say that every project (library, framework) must make efforts in this direction. It's not a good argument not to do it because others don't.

**Comment by lukasj** [comment]
there are no plans for 2.6.x to support JPMS.

eclipselink.jar used to contain some javax classes to keep compatibility with JPA 2.0. There should be 2 options for you to try:

* use `org.eclipse.persistence:javax.persistence:2.0.5` together with `org.eclipse.persistence:eclipselink:2.7.8` (...required JPA 2.1+ classes are supposed to be brought in by the latter as long as you stay on the classpath)

OR

* use `jakarta.persistence:jakarta.persistence:2.2.3` together with `org.eclipse.persistence:org.eclipse.persistence.jpa:2.7.8` (there should be no split package problem in this case)


...generally speaking move towards jakarta.persistence:jakarta.persistence:3.0.0 and eclipselink 3.0.0 would be preferred (note that there is `javax.persistence`->`jakarta.persistence` package name change)
