### ISSUE TITLE
Poor performance of InformixPlatform with IDENTITY generated primary keys

### ISSUE THREAD

**Issue by sgflt** [eclipse-ee4j/eclipselink#968]
Method InformixPlatform#buildSelectQueryForIdentity creates following select:

`SELECT DISTINCT(DBINFO('sqlca.sqlerrd1')) FROM systables`

1) The 'sqlca. sqlerrd1' option returns a single integer that provides the last serial value that is inserted into a table. 
2) DISTINCT does not makes sense on sigle value
3) multiple values are produced by systables which may have hundreds of rows

Proposed fix:

`SELECT FIRST 1 DBINFO('sqlca.sqlerrd1') FROM systables`

**Comment by Fragnite-hub** [comment]
Can I work on this !!
