### ISSUE TITLE
Update downloads page

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/eclipselink#996]
to reflect recent changes wrt P2 site (not available any more for 3+) and changed maven repo: https://www.eclipse.org/eclipselink/downloads/

**Comment by rfelcman** [comment]
It was fixed in https://www.eclipse.org/eclipselink/downloads/ via git (see https://git.eclipse.org/r/plugins/gitiles/www.eclipse.org/eclipselink/+/b5bc64feaf656ab2b73c3e3748f6ca38930665aa)
and Maven Wiki page changes was approved and published too see https://wiki.eclipse.org/EclipseLink/Maven.
