### ISSUE TITLE
broken metamodel generation for @NotNull byte[] with javaee 8 api

### ISSUE THREAD

**Issue by priyanahata** [eclipse-ee4j/eclipselink#998]
Issue described here

https://www.eclipse.org/forums/index.php/m/1836562/#msg_1836562

**Comment by lukasj** [comment]
The problem is JDK version related. Either downgrade your JDK or use EL 2.7.8.

**Comment by priyanahata** [comment]
Hi Lukas,

Using JDK 8, happens with u60 and u271, 
using E.L. 2.7.8 already

Problem still happening

**Comment by lukasj** [comment]
in that case we need exact and reproducible test case as the test introduced with the fix through ##967 is not failing...

**Comment by priyanahata** [comment]
Ok, can do

**Comment by priyanahata** [comment]
Ok, test case attached

[elmetamodelbug.zip](https://github.com/eclipse-ee4j/eclipselink/files/5822220/elmetamodelbug.zip)

**Comment by priyanahata** [comment]
hey Lukas, can we reopen?

**Comment by lukasj** [comment]
It works well on JDK 11/15 but not on 8. Interesting...

**Comment by lukasj** [comment]
...and it works well in 3.0.0. So this is JDK specific issue in 2.7 only...

**Comment by priyanahata** [comment]
Funny enough, the last time i chatted with you about 6 years ago, it was due to an issue when upgrading from JDK 7 to JDK 8

**Comment by priyanahata** [comment]
And also only with the javaee 8 apis, 7 and 9 are fine

**Comment by priyanahata** [comment]
Lukas, for me, the issue also occurs on JDK 15 too

**Comment by priyanahata** [comment]
for me, it also happens in 2.6.3

**Comment by lukasj** [comment]
I got it. The problem is that on jdk8, returned String from TypeMirror.toString() looks like: `(@org.ann.NotNull :: byte)` while on jdk11 it looks like: `@org.ann.NotNull :: byte` and I apparently forgot to backport #601 which deals with this properly. Shame on me... :-/

**Comment by priyanahata** [comment]
Ok, so whats the plan? patch it on a 2.7.9 or what?

**Comment by lukasj** [comment]
there will 2.7.9 with the fix at some point

**Comment by priyanahata** [comment]
ok, if were to get $100 for guessing the date of the 2.7.9, what would your guess be?

**Comment by lukasj** [comment]
Q1 21.

**Comment by rfelcman** [comment]
If You need compiled binaries e.g. for testing You can use/download them from:

1. https://www.eclipse.org/eclipselink/downloads/nightly.php (2.7.9 part)

1. In Maven environment use snapshots repo https://jakarta.oss.sonatype.org/content/repositories/snapshots/ version `2.7.9-SNAPSHOT`
e.g.

```
       ...
        <profile>
            <id>snapshots</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <repositories>
                <repository>
                    <id>sonatype-nexus-snapshots</id>
                    <name>Sonatype Nexus Snapshots</name>
                    <url>https://jakarta.oss.sonatype.org/content/repositories/snapshots/</url>
                    <layout>default</layout>
                    <releases>
                        <enabled>false</enabled>
                        <updatePolicy>always</updatePolicy>
                        <checksumPolicy>warn</checksumPolicy>
                    </releases>
                    <snapshots>
                        <enabled>true</enabled>
                        <updatePolicy>never</updatePolicy>
                        <checksumPolicy>fail</checksumPolicy>
                    </snapshots>
                </repository>
            </repositories>
        </profile>
         ...
```

**Comment by priyanahata** [comment]
Owe you $100
